// Generated by Bisonc++ V4.01.00 on Thu, 14 Mar 2013 21:21:42 -0300

// $insert class.ih
#include "mdparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {300, 1}, // 1: input ->  declaration_seq
     {301, 0}, // 2: declaration_seq ->  <empty>
     {301, 2}, // 3: declaration_seq ->  declaration_seq declaration
     {302, 1}, // 4: declaration ->  block_declaration
     {302, 1}, // 5: declaration ->  namespace_definition
     {303, 1}, // 6: block_declaration ->  simple_declaration
     {305, 1}, // 7: simple_declaration (';') ->  ';'
     {305, 3}, // 8: simple_declaration (';') ->  decl_specifier_seq init_declarator_list ';'
     {305, 2}, // 9: simple_declaration (';') ->  decl_specifier_seq ';'
     {305, 2}, // 10: simple_declaration (';') ->  init_declarator_list ';'
     {306, 1}, // 11: decl_specifier_seq ->  type_specifier
     {306, 2}, // 12: decl_specifier_seq ->  decl_specifier decl_specifier_seq
     {309, 1}, // 13: decl_specifier (FRIEND) ->  FRIEND
     {309, 1}, // 14: decl_specifier (TYPEDEF) ->  TYPEDEF
     {307, 1}, // 15: init_declarator_list ->  init_declarator
     {307, 3}, // 16: init_declarator_list (',') ->  init_declarator_list ',' init_declarator
     {310, 1}, // 17: init_declarator ->  declarator
     {310, 2}, // 18: init_declarator ->  declarator initializer
     {311, 1}, // 19: declarator ->  ptr_declarator
     {313, 1}, // 20: ptr_declarator ->  noptr_declarator
     {313, 2}, // 21: ptr_declarator ->  ptr_operator declarator
     {314, 1}, // 22: noptr_declarator ->  declarator_id
     {314, 4}, // 23: noptr_declarator ('[') ->  noptr_declarator '[' expression ']'
     {314, 3}, // 24: noptr_declarator ('(') ->  '(' ptr_declarator ')'
     {315, 1}, // 25: ptr_operator ('*') ->  '*'
     {315, 1}, // 26: ptr_operator ('&') ->  '&'
     {316, 1}, // 27: declarator_id ->  identifier
     {312, 1}, // 28: initializer ->  brace_or_equal_initializer
     {319, 2}, // 29: brace_or_equal_initializer ('=') ->  '=' initializer_clause
     {320, 1}, // 30: initializer_clause ->  expression
     {304, 1}, // 31: namespace_definition ->  named_namespace_definition
     {304, 1}, // 32: namespace_definition ->  unnamed_namespace_definition
     {321, 5}, // 33: named_namespace_definition (NAMESPACE) ->  NAMESPACE identifier '{' declaration_seq '}'
     {321, 6}, // 34: named_namespace_definition (INLINE) ->  INLINE NAMESPACE identifier '{' declaration_seq '}'
     {322, 4}, // 35: unnamed_namespace_definition (NAMESPACE) ->  NAMESPACE '{' declaration_seq '}'
     {322, 5}, // 36: unnamed_namespace_definition (INLINE) ->  INLINE NAMESPACE '{' declaration_seq '}'
     {308, 1}, // 37: type_specifier ->  trailing_type_specifier
     {323, 1}, // 38: trailing_type_specifier ->  simple_type_specifier
     {324, 1}, // 39: simple_type_specifier ->  type_name
     {325, 1}, // 40: type_name ->  identifier
     {317, 1}, // 41: expression ->  term
     {317, 2}, // 42: expression ->  expression term
     {326, 1}, // 43: term ->  literal
     {326, 1}, // 44: term ->  identifier
     {326, 1}, // 45: term ->  operand
     {326, 3}, // 46: term ('(') ->  '(' expression ')'
     {327, 1}, // 47: literal (STRING_LITERAL) ->  STRING_LITERAL
     {327, 1}, // 48: literal (CHARACTER_LITERAL) ->  CHARACTER_LITERAL
     {327, 1}, // 49: literal (INTEGER_LITERAL) ->  INTEGER_LITERAL
     {327, 1}, // 50: literal (HEXADECIMAL_LITERAL) ->  HEXADECIMAL_LITERAL
     {327, 1}, // 51: literal (OCTAL_LITERAL) ->  OCTAL_LITERAL
     {327, 1}, // 52: literal (FLOAT_LITERAL) ->  FLOAT_LITERAL
     {328, 1}, // 53: operand ('+') ->  '+'
     {328, 1}, // 54: operand ('-') ->  '-'
     {328, 1}, // 55: operand ('*') ->  '*'
     {328, 1}, // 56: operand ('/') ->  '/'
     {328, 1}, // 57: operand ('%') ->  '%'
     {328, 1}, // 58: operand ('^') ->  '^'
     {328, 1}, // 59: operand ('?') ->  '?'
     {328, 1}, // 60: operand (':') ->  ':'
     {318, 1}, // 61: identifier (IDENTIFIER) ->  IDENTIFIER
     {329, 1}, // 62: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  3} },                   
    { {     300}, {  1} }, // input          
    { {     301}, {  2} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 30} },                                
    { {     302}, {  3} }, // declaration                 
    { {     303}, {  4} }, // block_declaration           
    { {     304}, {  5} }, // namespace_definition        
    { {     305}, {  6} }, // simple_declaration          
    { {     321}, {  7} }, // named_namespace_definition  
    { {     322}, {  8} }, // unnamed_namespace_definition
    { {      59}, {  9} }, // ';'                         
    { {     306}, { 10} }, // decl_specifier_seq          
    { {     307}, { 11} }, // init_declarator_list        
    { {     270}, { 12} }, // NAMESPACE                   
    { {     268}, { 13} }, // INLINE                      
    { {     308}, { 14} }, // type_specifier              
    { {     309}, { 15} }, // decl_specifier              
    { {     310}, { 16} }, // init_declarator             
    { {     323}, { 17} }, // trailing_type_specifier     
    { {     267}, { 18} }, // FRIEND                      
    { {     285}, { 19} }, // TYPEDEF                     
    { {     311}, { 20} }, // declarator                  
    { {     324}, { 21} }, // simple_type_specifier       
    { {     313}, { 22} }, // ptr_declarator              
    { {     325}, { 23} }, // type_name                   
    { {     314}, { 24} }, // noptr_declarator            
    { {     315}, { 25} }, // ptr_operator                
    { {     318}, { 26} }, // identifier                  
    { {     316}, { 27} }, // declarator_id               
    { {      40}, { 28} }, // '('                         
    { {      42}, { 29} }, // '*'                         
    { {      38}, { 30} }, // '&'                         
    { {     257}, { 31} }, // IDENTIFIER                  
    { {       0}, { -1} },                                
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       307}, { 32} }, // init_declarator_list
    { {        59}, { 33} }, // ';'                 
    { {       310}, { 16} }, // init_declarator     
    { {       311}, { 20} }, // declarator          
    { {       313}, { 22} }, // ptr_declarator      
    { {       314}, { 24} }, // noptr_declarator    
    { {       315}, { 25} }, // ptr_operator        
    { {       316}, { 27} }, // declarator_id       
    { {        40}, { 28} }, // '('                 
    { {        42}, { 29} }, // '*'                 
    { {        38}, { 30} }, // '&'                 
    { {       318}, { 34} }, // identifier          
    { {       257}, { 31} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 35} }, // ';'
    { {        44}, { 36} }, // ','
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       318}, { 37} }, // identifier
    { {       123}, { 38} }, // '{'       
    { {       257}, { 31} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       270}, { 39} }, // NAMESPACE
    { {         0}, {  0} },             
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, { 11} },                           
    { {       306}, { 40} }, // decl_specifier_seq     
    { {       308}, { 14} }, // type_specifier         
    { {       309}, { 15} }, // decl_specifier         
    { {       323}, { 17} }, // trailing_type_specifier
    { {       267}, { 18} }, // FRIEND                 
    { {       285}, { 19} }, // TYPEDEF                
    { {       324}, { 21} }, // simple_type_specifier  
    { {       325}, { 23} }, // type_name              
    { {       318}, { 41} }, // identifier             
    { {       257}, { 31} }, // IDENTIFIER             
    { {         0}, {  0} },                           
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_20[] =
{
    { { REQ_DEF}, {   4} },                              
    { {     312}, {  42} }, // initializer               
    { {     319}, {  43} }, // brace_or_equal_initializer
    { {      61}, {  44} }, // '='                       
    { {       0}, { -17} },                              
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_24[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  45} }, // '['
    { {       0}, { -20} },       
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       311}, { 46} }, // declarator      
    { {       313}, { 22} }, // ptr_declarator  
    { {       314}, { 24} }, // noptr_declarator
    { {       315}, { 25} }, // ptr_operator    
    { {       316}, { 27} }, // declarator_id   
    { {        40}, { 28} }, // '('             
    { {        42}, { 29} }, // '*'             
    { {        38}, { 30} }, // '&'             
    { {       318}, { 34} }, // identifier      
    { {       257}, { 31} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_26[] =
{
    { { REQ_DEF}, {   5} },              
    { {     257}, { -40} }, // IDENTIFIER
    { {      40}, { -40} }, // '('       
    { {      42}, { -40} }, // '*'       
    { {      38}, { -40} }, // '&'       
    { {       0}, { -27} },              
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       313}, { 47} }, // ptr_declarator  
    { {       314}, { 24} }, // noptr_declarator
    { {       315}, { 25} }, // ptr_operator    
    { {       316}, { 27} }, // declarator_id   
    { {        40}, { 28} }, // '('             
    { {        42}, { 29} }, // '*'             
    { {        38}, { 30} }, // '&'             
    { {       318}, { 34} }, // identifier      
    { {       257}, { 31} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 48} }, // ';'
    { {        44}, { 36} }, // ','
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 12} },                    
    { {       310}, { 49} }, // init_declarator 
    { {       311}, { 20} }, // declarator      
    { {       313}, { 22} }, // ptr_declarator  
    { {       314}, { 24} }, // noptr_declarator
    { {       315}, { 25} }, // ptr_operator    
    { {       316}, { 27} }, // declarator_id   
    { {        40}, { 28} }, // '('             
    { {        42}, { 29} }, // '*'             
    { {        38}, { 30} }, // '&'             
    { {       318}, { 34} }, // identifier      
    { {       257}, { 31} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 50} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { DEF_RED}, {  2} },                   
    { {     301}, { 51} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       318}, { 52} }, // identifier
    { {       123}, { 53} }, // '{'       
    { {       257}, { 31} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 23} },                       
    { {       320}, { 54} }, // initializer_clause 
    { {       317}, { 55} }, // expression         
    { {       326}, { 56} }, // term               
    { {       327}, { 57} }, // literal            
    { {       318}, { 58} }, // identifier         
    { {       328}, { 59} }, // operand            
    { {        40}, { 60} }, // '('                
    { {       294}, { 61} }, // STRING_LITERAL     
    { {       295}, { 62} }, // CHARACTER_LITERAL  
    { {       296}, { 63} }, // INTEGER_LITERAL    
    { {       297}, { 64} }, // HEXADECIMAL_LITERAL
    { {       298}, { 65} }, // OCTAL_LITERAL      
    { {       299}, { 66} }, // FLOAT_LITERAL      
    { {       257}, { 31} }, // IDENTIFIER         
    { {        43}, { 67} }, // '+'                
    { {        45}, { 68} }, // '-'                
    { {        42}, { 69} }, // '*'                
    { {        47}, { 70} }, // '/'                
    { {        37}, { 71} }, // '%'                
    { {        94}, { 72} }, // '^'                
    { {        63}, { 73} }, // '?'                
    { {        58}, { 74} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {       317}, { 75} }, // expression         
    { {       326}, { 56} }, // term               
    { {       327}, { 57} }, // literal            
    { {       318}, { 58} }, // identifier         
    { {       328}, { 59} }, // operand            
    { {        40}, { 60} }, // '('                
    { {       294}, { 61} }, // STRING_LITERAL     
    { {       295}, { 62} }, // CHARACTER_LITERAL  
    { {       296}, { 63} }, // INTEGER_LITERAL    
    { {       297}, { 64} }, // HEXADECIMAL_LITERAL
    { {       298}, { 65} }, // OCTAL_LITERAL      
    { {       299}, { 66} }, // FLOAT_LITERAL      
    { {       257}, { 31} }, // IDENTIFIER         
    { {        43}, { 67} }, // '+'                
    { {        45}, { 68} }, // '-'                
    { {        42}, { 69} }, // '*'                
    { {        47}, { 70} }, // '/'                
    { {        37}, { 71} }, // '%'                
    { {        94}, { 72} }, // '^'                
    { {        63}, { 73} }, // '?'                
    { {        58}, { 74} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 76} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_48[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {  2} },                   
    { {     301}, { 77} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 31} },                                
    { {       125}, { 78} }, // '}'                         
    { {       302}, {  3} }, // declaration                 
    { {       303}, {  4} }, // block_declaration           
    { {       304}, {  5} }, // namespace_definition        
    { {       305}, {  6} }, // simple_declaration          
    { {       321}, {  7} }, // named_namespace_definition  
    { {       322}, {  8} }, // unnamed_namespace_definition
    { {        59}, {  9} }, // ';'                         
    { {       306}, { 10} }, // decl_specifier_seq          
    { {       307}, { 11} }, // init_declarator_list        
    { {       270}, { 12} }, // NAMESPACE                   
    { {       268}, { 13} }, // INLINE                      
    { {       308}, { 14} }, // type_specifier              
    { {       309}, { 15} }, // decl_specifier              
    { {       310}, { 16} }, // init_declarator             
    { {       323}, { 17} }, // trailing_type_specifier     
    { {       267}, { 18} }, // FRIEND                      
    { {       285}, { 19} }, // TYPEDEF                     
    { {       311}, { 20} }, // declarator                  
    { {       324}, { 21} }, // simple_type_specifier       
    { {       313}, { 22} }, // ptr_declarator              
    { {       325}, { 23} }, // type_name                   
    { {       314}, { 24} }, // noptr_declarator            
    { {       315}, { 25} }, // ptr_operator                
    { {       318}, { 26} }, // identifier                  
    { {       316}, { 27} }, // declarator_id               
    { {        40}, { 28} }, // '('                         
    { {        42}, { 29} }, // '*'                         
    { {        38}, { 30} }, // '&'                         
    { {       257}, { 31} }, // IDENTIFIER                  
    { {         0}, {  0} },                                
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 79} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_53[] =
{
    { { DEF_RED}, {  2} },                   
    { {     301}, { 80} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_55[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     326}, {  81} }, // term               
    { {     327}, {  57} }, // literal            
    { {     318}, {  58} }, // identifier         
    { {     328}, {  59} }, // operand            
    { {      40}, {  60} }, // '('                
    { {     294}, {  61} }, // STRING_LITERAL     
    { {     295}, {  62} }, // CHARACTER_LITERAL  
    { {     296}, {  63} }, // INTEGER_LITERAL    
    { {     297}, {  64} }, // HEXADECIMAL_LITERAL
    { {     298}, {  65} }, // OCTAL_LITERAL      
    { {     299}, {  66} }, // FLOAT_LITERAL      
    { {     257}, {  31} }, // IDENTIFIER         
    { {      43}, {  67} }, // '+'                
    { {      45}, {  68} }, // '-'                
    { {      42}, {  69} }, // '*'                
    { {      47}, {  70} }, // '/'                
    { {      37}, {  71} }, // '%'                
    { {      94}, {  72} }, // '^'                
    { {      63}, {  73} }, // '?'                
    { {      58}, {  74} }, // ':'                
    { {       0}, { -30} },                       
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {       317}, { 82} }, // expression         
    { {       326}, { 56} }, // term               
    { {       327}, { 57} }, // literal            
    { {       318}, { 58} }, // identifier         
    { {       328}, { 59} }, // operand            
    { {        40}, { 60} }, // '('                
    { {       294}, { 61} }, // STRING_LITERAL     
    { {       295}, { 62} }, // CHARACTER_LITERAL  
    { {       296}, { 63} }, // INTEGER_LITERAL    
    { {       297}, { 64} }, // HEXADECIMAL_LITERAL
    { {       298}, { 65} }, // OCTAL_LITERAL      
    { {       299}, { 66} }, // FLOAT_LITERAL      
    { {       257}, { 31} }, // IDENTIFIER         
    { {        43}, { 67} }, // '+'                
    { {        45}, { 68} }, // '-'                
    { {        42}, { 69} }, // '*'                
    { {        47}, { 70} }, // '/'                
    { {        37}, { 71} }, // '%'                
    { {        94}, { 72} }, // '^'                
    { {        63}, { 73} }, // '?'                
    { {        58}, { 74} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {        93}, { 83} }, // ']'                
    { {       326}, { 81} }, // term               
    { {       327}, { 57} }, // literal            
    { {       318}, { 58} }, // identifier         
    { {       328}, { 59} }, // operand            
    { {        40}, { 60} }, // '('                
    { {       294}, { 61} }, // STRING_LITERAL     
    { {       295}, { 62} }, // CHARACTER_LITERAL  
    { {       296}, { 63} }, // INTEGER_LITERAL    
    { {       297}, { 64} }, // HEXADECIMAL_LITERAL
    { {       298}, { 65} }, // OCTAL_LITERAL      
    { {       299}, { 66} }, // FLOAT_LITERAL      
    { {       257}, { 31} }, // IDENTIFIER         
    { {        43}, { 67} }, // '+'                
    { {        45}, { 68} }, // '-'                
    { {        42}, { 69} }, // '*'                
    { {        47}, { 70} }, // '/'                
    { {        37}, { 71} }, // '%'                
    { {        94}, { 72} }, // '^'                
    { {        63}, { 73} }, // '?'                
    { {        58}, { 74} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 31} },                                
    { {       125}, { 84} }, // '}'                         
    { {       302}, {  3} }, // declaration                 
    { {       303}, {  4} }, // block_declaration           
    { {       304}, {  5} }, // namespace_definition        
    { {       305}, {  6} }, // simple_declaration          
    { {       321}, {  7} }, // named_namespace_definition  
    { {       322}, {  8} }, // unnamed_namespace_definition
    { {        59}, {  9} }, // ';'                         
    { {       306}, { 10} }, // decl_specifier_seq          
    { {       307}, { 11} }, // init_declarator_list        
    { {       270}, { 12} }, // NAMESPACE                   
    { {       268}, { 13} }, // INLINE                      
    { {       308}, { 14} }, // type_specifier              
    { {       309}, { 15} }, // decl_specifier              
    { {       310}, { 16} }, // init_declarator             
    { {       323}, { 17} }, // trailing_type_specifier     
    { {       267}, { 18} }, // FRIEND                      
    { {       285}, { 19} }, // TYPEDEF                     
    { {       311}, { 20} }, // declarator                  
    { {       324}, { 21} }, // simple_type_specifier       
    { {       313}, { 22} }, // ptr_declarator              
    { {       325}, { 23} }, // type_name                   
    { {       314}, { 24} }, // noptr_declarator            
    { {       315}, { 25} }, // ptr_operator                
    { {       318}, { 26} }, // identifier                  
    { {       316}, { 27} }, // declarator_id               
    { {        40}, { 28} }, // '('                         
    { {        42}, { 29} }, // '*'                         
    { {        38}, { 30} }, // '&'                         
    { {       257}, { 31} }, // IDENTIFIER                  
    { {         0}, {  0} },                                
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {  2} },                   
    { {     301}, { 85} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, { 31} },                                
    { {       125}, { 86} }, // '}'                         
    { {       302}, {  3} }, // declaration                 
    { {       303}, {  4} }, // block_declaration           
    { {       304}, {  5} }, // namespace_definition        
    { {       305}, {  6} }, // simple_declaration          
    { {       321}, {  7} }, // named_namespace_definition  
    { {       322}, {  8} }, // unnamed_namespace_definition
    { {        59}, {  9} }, // ';'                         
    { {       306}, { 10} }, // decl_specifier_seq          
    { {       307}, { 11} }, // init_declarator_list        
    { {       270}, { 12} }, // NAMESPACE                   
    { {       268}, { 13} }, // INLINE                      
    { {       308}, { 14} }, // type_specifier              
    { {       309}, { 15} }, // decl_specifier              
    { {       310}, { 16} }, // init_declarator             
    { {       323}, { 17} }, // trailing_type_specifier     
    { {       267}, { 18} }, // FRIEND                      
    { {       285}, { 19} }, // TYPEDEF                     
    { {       311}, { 20} }, // declarator                  
    { {       324}, { 21} }, // simple_type_specifier       
    { {       313}, { 22} }, // ptr_declarator              
    { {       325}, { 23} }, // type_name                   
    { {       314}, { 24} }, // noptr_declarator            
    { {       315}, { 25} }, // ptr_operator                
    { {       318}, { 26} }, // identifier                  
    { {       316}, { 27} }, // declarator_id               
    { {        40}, { 28} }, // '('                         
    { {        42}, { 29} }, // '*'                         
    { {        38}, { 30} }, // '&'                         
    { {       257}, { 31} }, // IDENTIFIER                  
    { {         0}, {  0} },                                
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {        41}, { 87} }, // ')'                
    { {       326}, { 81} }, // term               
    { {       327}, { 57} }, // literal            
    { {       318}, { 58} }, // identifier         
    { {       328}, { 59} }, // operand            
    { {        40}, { 60} }, // '('                
    { {       294}, { 61} }, // STRING_LITERAL     
    { {       295}, { 62} }, // CHARACTER_LITERAL  
    { {       296}, { 63} }, // INTEGER_LITERAL    
    { {       297}, { 64} }, // HEXADECIMAL_LITERAL
    { {       298}, { 65} }, // OCTAL_LITERAL      
    { {       299}, { 66} }, // FLOAT_LITERAL      
    { {       257}, { 31} }, // IDENTIFIER         
    { {        43}, { 67} }, // '+'                
    { {        45}, { 68} }, // '-'                
    { {        42}, { 69} }, // '*'                
    { {        47}, { 70} }, // '/'                
    { {        37}, { 71} }, // '%'                
    { {        94}, { 72} }, // '^'                
    { {        63}, { 73} }, // '?'                
    { {        58}, { 74} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, { 31} },                                
    { {       125}, { 88} }, // '}'                         
    { {       302}, {  3} }, // declaration                 
    { {       303}, {  4} }, // block_declaration           
    { {       304}, {  5} }, // namespace_definition        
    { {       305}, {  6} }, // simple_declaration          
    { {       321}, {  7} }, // named_namespace_definition  
    { {       322}, {  8} }, // unnamed_namespace_definition
    { {        59}, {  9} }, // ';'                         
    { {       306}, { 10} }, // decl_specifier_seq          
    { {       307}, { 11} }, // init_declarator_list        
    { {       270}, { 12} }, // NAMESPACE                   
    { {       268}, { 13} }, // INLINE                      
    { {       308}, { 14} }, // type_specifier              
    { {       309}, { 15} }, // decl_specifier              
    { {       310}, { 16} }, // init_declarator             
    { {       323}, { 17} }, // trailing_type_specifier     
    { {       267}, { 18} }, // FRIEND                      
    { {       285}, { 19} }, // TYPEDEF                     
    { {       311}, { 20} }, // declarator                  
    { {       324}, { 21} }, // simple_type_specifier       
    { {       313}, { 22} }, // ptr_declarator              
    { {       325}, { 23} }, // type_name                   
    { {       314}, { 24} }, // noptr_declarator            
    { {       315}, { 25} }, // ptr_operator                
    { {       318}, { 26} }, // identifier                  
    { {       316}, { 27} }, // declarator_id               
    { {        40}, { 28} }, // '('                         
    { {        42}, { 29} }, // '*'                         
    { {        38}, { 30} }, // '&'                         
    { {       257}, { 31} }, // IDENTIFIER                  
    { {         0}, {  0} },                                
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,
};

} // anonymous namespace ends


// $insert namespace-open
namespace opwig
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

MDParserBase::MDParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void MDParser::print__()
{
// $insert print
}

void MDParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void MDParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void MDParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void MDParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void MDParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t MDParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void MDParser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 55 "mdparser.gr"
        {}
        break;

        case 3:
#line 61 "mdparser.gr"
        {}
        break;

        case 5:
#line 67 "mdparser.gr"
        { std::cout << "Namespace definition" << std::endl; }
        break;

        case 6:
#line 75 "mdparser.gr"
        { std::cout << "Simple declaration" << std::endl; }
        break;

    }
}

inline void MDParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void MDParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int MDParser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void MDParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int MDParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}


// $insert namespace-close
}


