// Generated by Bisonc++ V4.01.00 on Thu, 14 Mar 2013 11:21:54 -0300

// $insert class.ih
#include "mdparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {265, 1}, // 1: input ->  declaration_seq
     {266, 0}, // 2: declaration_seq ->  <empty>
     {266, 2}, // 3: declaration_seq ->  declaration_seq declaration
     {267, 1}, // 4: declaration ->  block_declaration
     {268, 1}, // 5: block_declaration ->  simple_declaration
     {269, 1}, // 6: simple_declaration (';') ->  ';'
     {269, 3}, // 7: simple_declaration (';') ->  decl_specifier_seq init_declarator_list ';'
     {269, 2}, // 8: simple_declaration (';') ->  decl_specifier_seq ';'
     {269, 2}, // 9: simple_declaration (';') ->  init_declarator_list ';'
     {270, 1}, // 10: decl_specifier_seq ->  decl_specifier
     {270, 2}, // 11: decl_specifier_seq ->  decl_specifier decl_specifier_seq
     {272, 1}, // 12: decl_specifier ->  type_specifier
     {271, 1}, // 13: init_declarator_list ->  init_declarator
     {271, 3}, // 14: init_declarator_list (',') ->  init_declarator_list ',' init_declarator
     {274, 1}, // 15: init_declarator ->  declarator
     {274, 2}, // 16: init_declarator ->  declarator initializer
     {275, 1}, // 17: declarator ->  ptr_declarator
     {277, 1}, // 18: ptr_declarator ->  noptr_declarator
     {277, 2}, // 19: ptr_declarator ->  ptr_operator declarator
     {278, 1}, // 20: noptr_declarator ->  declarator_id
     {278, 4}, // 21: noptr_declarator ('[') ->  noptr_declarator '[' expression ']'
     {278, 3}, // 22: noptr_declarator ('(') ->  '(' ptr_declarator ')'
     {279, 1}, // 23: ptr_operator ('*') ->  '*'
     {279, 1}, // 24: ptr_operator ('&') ->  '&'
     {280, 1}, // 25: declarator_id ->  identifier
     {276, 1}, // 26: initializer ->  brace_or_equal_initializer
     {283, 2}, // 27: brace_or_equal_initializer ('=') ->  '=' initializer_clause
     {284, 1}, // 28: initializer_clause ->  expression
     {273, 1}, // 29: type_specifier ->  trailing_type_specifier
     {285, 1}, // 30: trailing_type_specifier ->  simple_type_specifier
     {286, 1}, // 31: simple_type_specifier ->  type_name
     {287, 1}, // 32: type_name ->  identifier
     {281, 1}, // 33: expression ->  term
     {281, 2}, // 34: expression ->  expression term
     {288, 1}, // 35: term ->  literal
     {288, 1}, // 36: term ->  identifier
     {288, 1}, // 37: term ->  operand
     {288, 3}, // 38: term ('(') ->  '(' expression ')'
     {289, 1}, // 39: literal (STRING_LITERAL) ->  STRING_LITERAL
     {289, 1}, // 40: literal (CHARACTER_LITERAL) ->  CHARACTER_LITERAL
     {289, 1}, // 41: literal (INTEGER_LITERAL) ->  INTEGER_LITERAL
     {289, 1}, // 42: literal (HEXADECIMAL_LITERAL) ->  HEXADECIMAL_LITERAL
     {289, 1}, // 43: literal (OCTAL_LITERAL) ->  OCTAL_LITERAL
     {289, 1}, // 44: literal (FLOAT_LITERAL) ->  FLOAT_LITERAL
     {290, 1}, // 45: operand ('+') ->  '+'
     {290, 1}, // 46: operand ('-') ->  '-'
     {290, 1}, // 47: operand ('*') ->  '*'
     {290, 1}, // 48: operand ('/') ->  '/'
     {290, 1}, // 49: operand ('%') ->  '%'
     {290, 1}, // 50: operand ('^') ->  '^'
     {290, 1}, // 51: operand ('?') ->  '?'
     {290, 1}, // 52: operand (':') ->  ':'
     {282, 1}, // 53: identifier (IDENTIFIER) ->  IDENTIFIER
     {291, 1}, // 54: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  3} },                   
    { {     265}, {  1} }, // input          
    { {     266}, {  2} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 23} },                           
    { {     267}, {  3} }, // declaration            
    { {     268}, {  4} }, // block_declaration      
    { {     269}, {  5} }, // simple_declaration     
    { {      59}, {  6} }, // ';'                    
    { {     270}, {  7} }, // decl_specifier_seq     
    { {     271}, {  8} }, // init_declarator_list   
    { {     272}, {  9} }, // decl_specifier         
    { {     274}, { 10} }, // init_declarator        
    { {     273}, { 11} }, // type_specifier         
    { {     275}, { 12} }, // declarator             
    { {     285}, { 13} }, // trailing_type_specifier
    { {     277}, { 14} }, // ptr_declarator         
    { {     286}, { 15} }, // simple_type_specifier  
    { {     278}, { 16} }, // noptr_declarator       
    { {     279}, { 17} }, // ptr_operator           
    { {     287}, { 18} }, // type_name              
    { {     280}, { 19} }, // declarator_id          
    { {      40}, { 20} }, // '('                    
    { {      42}, { 21} }, // '*'                    
    { {      38}, { 22} }, // '&'                    
    { {     282}, { 23} }, // identifier             
    { {     257}, { 24} }, // IDENTIFIER             
    { {       0}, { -1} },                           
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       271}, { 25} }, // init_declarator_list
    { {        59}, { 26} }, // ';'                 
    { {       274}, { 10} }, // init_declarator     
    { {       275}, { 12} }, // declarator          
    { {       277}, { 14} }, // ptr_declarator      
    { {       278}, { 16} }, // noptr_declarator    
    { {       279}, { 17} }, // ptr_operator        
    { {       280}, { 19} }, // declarator_id       
    { {        40}, { 20} }, // '('                 
    { {        42}, { 21} }, // '*'                 
    { {        38}, { 22} }, // '&'                 
    { {       282}, { 27} }, // identifier          
    { {       257}, { 24} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 28} }, // ';'
    { {        44}, { 29} }, // ','
    { {         0}, {  0} },       
};

SR__ s_9[] =
{
    { { REQ_DEF}, {   9} },                           
    { {     270}, {  30} }, // decl_specifier_seq     
    { {     272}, {   9} }, // decl_specifier         
    { {     273}, {  11} }, // type_specifier         
    { {     285}, {  13} }, // trailing_type_specifier
    { {     286}, {  15} }, // simple_type_specifier  
    { {     287}, {  18} }, // type_name              
    { {     282}, {  31} }, // identifier             
    { {     257}, {  24} }, // IDENTIFIER             
    { {       0}, { -10} },                           
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_12[] =
{
    { { REQ_DEF}, {   4} },                              
    { {     276}, {  32} }, // initializer               
    { {     283}, {  33} }, // brace_or_equal_initializer
    { {      61}, {  34} }, // '='                       
    { {       0}, { -15} },                              
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_16[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  35} }, // '['
    { {       0}, { -18} },       
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       275}, { 36} }, // declarator      
    { {       277}, { 14} }, // ptr_declarator  
    { {       278}, { 16} }, // noptr_declarator
    { {       279}, { 17} }, // ptr_operator    
    { {       280}, { 19} }, // declarator_id   
    { {        40}, { 20} }, // '('             
    { {        42}, { 21} }, // '*'             
    { {        38}, { 22} }, // '&'             
    { {       282}, { 27} }, // identifier      
    { {       257}, { 24} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       277}, { 37} }, // ptr_declarator  
    { {       278}, { 16} }, // noptr_declarator
    { {       279}, { 17} }, // ptr_operator    
    { {       280}, { 19} }, // declarator_id   
    { {        40}, { 20} }, // '('             
    { {        42}, { 21} }, // '*'             
    { {        38}, { 22} }, // '&'             
    { {       282}, { 27} }, // identifier      
    { {       257}, { 24} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_23[] =
{
    { { REQ_DEF}, {   5} },              
    { {     257}, { -32} }, // IDENTIFIER
    { {      40}, { -32} }, // '('       
    { {      42}, { -32} }, // '*'       
    { {      38}, { -32} }, // '&'       
    { {       0}, { -25} },              
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 38} }, // ';'
    { {        44}, { 29} }, // ','
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, { 12} },                    
    { {       274}, { 39} }, // init_declarator 
    { {       275}, { 12} }, // declarator      
    { {       277}, { 14} }, // ptr_declarator  
    { {       278}, { 16} }, // noptr_declarator
    { {       279}, { 17} }, // ptr_operator    
    { {       280}, { 19} }, // declarator_id   
    { {        40}, { 20} }, // '('             
    { {        42}, { 21} }, // '*'             
    { {        38}, { 22} }, // '&'             
    { {       282}, { 27} }, // identifier      
    { {       257}, { 24} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 23} },                       
    { {       284}, { 40} }, // initializer_clause 
    { {       281}, { 41} }, // expression         
    { {       288}, { 42} }, // term               
    { {       289}, { 43} }, // literal            
    { {       282}, { 44} }, // identifier         
    { {       290}, { 45} }, // operand            
    { {        40}, { 46} }, // '('                
    { {       259}, { 47} }, // STRING_LITERAL     
    { {       260}, { 48} }, // CHARACTER_LITERAL  
    { {       261}, { 49} }, // INTEGER_LITERAL    
    { {       262}, { 50} }, // HEXADECIMAL_LITERAL
    { {       263}, { 51} }, // OCTAL_LITERAL      
    { {       264}, { 52} }, // FLOAT_LITERAL      
    { {       257}, { 24} }, // IDENTIFIER         
    { {        43}, { 53} }, // '+'                
    { {        45}, { 54} }, // '-'                
    { {        42}, { 55} }, // '*'                
    { {        47}, { 56} }, // '/'                
    { {        37}, { 57} }, // '%'                
    { {        94}, { 58} }, // '^'                
    { {        63}, { 59} }, // '?'                
    { {        58}, { 60} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {       281}, { 61} }, // expression         
    { {       288}, { 42} }, // term               
    { {       289}, { 43} }, // literal            
    { {       282}, { 44} }, // identifier         
    { {       290}, { 45} }, // operand            
    { {        40}, { 46} }, // '('                
    { {       259}, { 47} }, // STRING_LITERAL     
    { {       260}, { 48} }, // CHARACTER_LITERAL  
    { {       261}, { 49} }, // INTEGER_LITERAL    
    { {       262}, { 50} }, // HEXADECIMAL_LITERAL
    { {       263}, { 51} }, // OCTAL_LITERAL      
    { {       264}, { 52} }, // FLOAT_LITERAL      
    { {       257}, { 24} }, // IDENTIFIER         
    { {        43}, { 53} }, // '+'                
    { {        45}, { 54} }, // '-'                
    { {        42}, { 55} }, // '*'                
    { {        47}, { 56} }, // '/'                
    { {        37}, { 57} }, // '%'                
    { {        94}, { 58} }, // '^'                
    { {        63}, { 59} }, // '?'                
    { {        58}, { 60} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 62} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_41[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     288}, {  63} }, // term               
    { {     289}, {  43} }, // literal            
    { {     282}, {  44} }, // identifier         
    { {     290}, {  45} }, // operand            
    { {      40}, {  46} }, // '('                
    { {     259}, {  47} }, // STRING_LITERAL     
    { {     260}, {  48} }, // CHARACTER_LITERAL  
    { {     261}, {  49} }, // INTEGER_LITERAL    
    { {     262}, {  50} }, // HEXADECIMAL_LITERAL
    { {     263}, {  51} }, // OCTAL_LITERAL      
    { {     264}, {  52} }, // FLOAT_LITERAL      
    { {     257}, {  24} }, // IDENTIFIER         
    { {      43}, {  53} }, // '+'                
    { {      45}, {  54} }, // '-'                
    { {      42}, {  55} }, // '*'                
    { {      47}, {  56} }, // '/'                
    { {      37}, {  57} }, // '%'                
    { {      94}, {  58} }, // '^'                
    { {      63}, {  59} }, // '?'                
    { {      58}, {  60} }, // ':'                
    { {       0}, { -28} },                       
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {       281}, { 64} }, // expression         
    { {       288}, { 42} }, // term               
    { {       289}, { 43} }, // literal            
    { {       282}, { 44} }, // identifier         
    { {       290}, { 45} }, // operand            
    { {        40}, { 46} }, // '('                
    { {       259}, { 47} }, // STRING_LITERAL     
    { {       260}, { 48} }, // CHARACTER_LITERAL  
    { {       261}, { 49} }, // INTEGER_LITERAL    
    { {       262}, { 50} }, // HEXADECIMAL_LITERAL
    { {       263}, { 51} }, // OCTAL_LITERAL      
    { {       264}, { 52} }, // FLOAT_LITERAL      
    { {       257}, { 24} }, // IDENTIFIER         
    { {        43}, { 53} }, // '+'                
    { {        45}, { 54} }, // '-'                
    { {        42}, { 55} }, // '*'                
    { {        47}, { 56} }, // '/'                
    { {        37}, { 57} }, // '%'                
    { {        94}, { 58} }, // '^'                
    { {        63}, { 59} }, // '?'                
    { {        58}, { 60} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {        93}, { 65} }, // ']'                
    { {       288}, { 63} }, // term               
    { {       289}, { 43} }, // literal            
    { {       282}, { 44} }, // identifier         
    { {       290}, { 45} }, // operand            
    { {        40}, { 46} }, // '('                
    { {       259}, { 47} }, // STRING_LITERAL     
    { {       260}, { 48} }, // CHARACTER_LITERAL  
    { {       261}, { 49} }, // INTEGER_LITERAL    
    { {       262}, { 50} }, // HEXADECIMAL_LITERAL
    { {       263}, { 51} }, // OCTAL_LITERAL      
    { {       264}, { 52} }, // FLOAT_LITERAL      
    { {       257}, { 24} }, // IDENTIFIER         
    { {        43}, { 53} }, // '+'                
    { {        45}, { 54} }, // '-'                
    { {        42}, { 55} }, // '*'                
    { {        47}, { 56} }, // '/'                
    { {        37}, { 57} }, // '%'                
    { {        94}, { 58} }, // '^'                
    { {        63}, { 59} }, // '?'                
    { {        58}, { 60} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {        41}, { 66} }, // ')'                
    { {       288}, { 63} }, // term               
    { {       289}, { 43} }, // literal            
    { {       282}, { 44} }, // identifier         
    { {       290}, { 45} }, // operand            
    { {        40}, { 46} }, // '('                
    { {       259}, { 47} }, // STRING_LITERAL     
    { {       260}, { 48} }, // CHARACTER_LITERAL  
    { {       261}, { 49} }, // INTEGER_LITERAL    
    { {       262}, { 50} }, // HEXADECIMAL_LITERAL
    { {       263}, { 51} }, // OCTAL_LITERAL      
    { {       264}, { 52} }, // FLOAT_LITERAL      
    { {       257}, { 24} }, // IDENTIFIER         
    { {        43}, { 53} }, // '+'                
    { {        45}, { 54} }, // '-'                
    { {        42}, { 55} }, // '*'                
    { {        47}, { 56} }, // '/'                
    { {        37}, { 57} }, // '%'                
    { {        94}, { 58} }, // '^'                
    { {        63}, { 59} }, // '?'                
    { {        58}, { 60} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,
};

} // anonymous namespace ends


// $insert namespace-open
namespace opwig
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

MDParserBase::MDParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void MDParser::print__()
{
// $insert print
}

void MDParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void MDParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void MDParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void MDParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void MDParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t MDParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void MDParser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 20 "mdparser.gr"
        {}
        break;

        case 3:
#line 26 "mdparser.gr"
        {}
        break;

        case 5:
#line 38 "mdparser.gr"
        { std::cout << "Simple declaration" << std::endl; }
        break;

    }
}

inline void MDParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void MDParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int MDParser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void MDParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int MDParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}


// $insert namespace-close
}


