#ifndef OUROBOROS_CONFIG_CONFIG_H_
#define OUROBOROS_CONFIG_CONFIG_H_

// Version
#define OUROBOROS_VERSION_MAJOR 
#define OUROBOROS_VERSION_MINOR 
#define OUROBOROS_VERSION_PATCH 

#define OUROBOROS_BIGVERSION ""
#define OUROBOROS_VERSION ""

///


///

#define OUROBOROS_CREATE_BINDINGS
#define OUROBOROS_LUA_BINDINGS
#define OUROBOROS_PYTHON_BINDINGS
#define OUROBOROS_ENABLED(X) OUROBOROS_##X##_ENABLED

#endif // OUROBOROS_CONFIG_CONFIG_H_
