SET(OUROBOROS_LUA_SRC 
    ./src/ouroboros/languages/lua/auxlib.h 
    ./src/ouroboros/languages/lua/basegear.cc 
    ./src/ouroboros/languages/lua/basegear.h 
    ./src/ouroboros/languages/lua/bootstrapgear.cc 
    ./src/ouroboros/languages/lua/bootstrapgear.h 
    ./src/ouroboros/languages/lua/datagear.cc 
    ./src/ouroboros/languages/lua/datagear.h 
    ./src/ouroboros/languages/lua/defs.h 
    ./src/ouroboros/languages/lua/header.h 
    ./src/ouroboros/languages/lua/luadata.cc 
    ./src/ouroboros/languages/lua/luadata.h 
    ./src/ouroboros/languages/lua/luamodules.cc 
    ./src/ouroboros/languages/lua/luawrapper.cc 
    ./src/ouroboros/languages/lua/luawrapper.h 
    ./src/ouroboros/languages/lua/modules.h 
    ./src/ouroboros/languages/lua/primitive.h 
    ./src/ouroboros/languages/lua/state.h 
    ./src/ouroboros/languages/lua/swigluarun.h 
)
