SET(OUROBOROS_PYTHON_SRC 
    ./src/ouroboros/languages/python/modules.h 
    ./src/ouroboros/languages/python/pythondata.cc 
    ./src/ouroboros/languages/python/pythondata.h 
    ./src/ouroboros/languages/python/pythonmodules.cc 
    ./src/ouroboros/languages/python/pythonwrapper.cc 
    ./src/ouroboros/languages/python/pythonwrapper.h 
    ./src/ouroboros/languages/python/swigpyrun.h 
)
