// Generated by Bisonc++ V4.01.00 on Wed, 01 May 2013 19:41:16 -0300

// $insert class.ih
#include "mdparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {338, 1}, // 1: input ->  declaration_seq
     {339, 0}, // 2: declaration_seq ->  <empty>
     {339, 2}, // 3: declaration_seq ->  declaration_seq declaration
     {340, 1}, // 4: declaration ->  block_declaration
     {340, 1}, // 5: declaration ->  namespace_definition
     {341, 1}, // 6: block_declaration ->  simple_declaration
     {342, 1}, // 7: simple_declaration (';') ->  ';'
     {342, 3}, // 8: simple_declaration (';') ->  decl_specifier_seq init_declarator_list ';'
     {342, 2}, // 9: simple_declaration (';') ->  decl_specifier_seq ';'
     {342, 2}, // 10: simple_declaration (';') ->  init_declarator_list ';'
     {343, 1}, // 11: decl_specifier_seq ->  type_specifier
     {343, 2}, // 12: decl_specifier_seq ->  decl_specifier decl_specifier_seq
     {344, 1}, // 13: decl_specifier (FRIEND) ->  FRIEND
     {344, 1}, // 14: decl_specifier (TYPEDEF) ->  TYPEDEF
     {345, 1}, // 15: init_declarator_list ->  init_declarator
     {345, 3}, // 16: init_declarator_list (',') ->  init_declarator_list ',' init_declarator
     {346, 1}, // 17: init_declarator ->  declarator
     {346, 2}, // 18: init_declarator ->  declarator initializer
     {348, 1}, // 19: declarator ->  ptr_declarator
     {349, 1}, // 20: ptr_declarator ->  noptr_declarator
     {349, 2}, // 21: ptr_declarator ->  ptr_operator ptr_declarator
     {351, 1}, // 22: noptr_declarator ->  declarator_id
     {351, 1}, // 23: noptr_declarator ->  constructor_name
     {351, 2}, // 24: noptr_declarator ->  noptr_declarator parameters_and_qualifiers
     {351, 4}, // 25: noptr_declarator ('[') ->  noptr_declarator '[' expression ']'
     {351, 3}, // 26: noptr_declarator ('[') ->  noptr_declarator '[' ']'
     {351, 3}, // 27: noptr_declarator ('(') ->  '(' ptr_declarator ')'
     {353, 3}, // 28: parameters_and_qualifiers ('(') ->  '(' parameter_declaration_clause ')'
     {354, 0}, // 29: parameter_declaration_clause ->  <empty>
     {354, 1}, // 30: parameter_declaration_clause ->  parameter_declaration_list
     {355, 1}, // 31: parameter_declaration_list ->  parameter_declaration
     {355, 3}, // 32: parameter_declaration_list (',') ->  parameter_declaration_list ',' parameter_declaration
     {356, 1}, // 33: parameter_declaration ->  decl_specifier_seq
     {356, 2}, // 34: parameter_declaration ->  decl_specifier_seq declarator
     {357, 0}, // 35: cv_qualifier_seq ->  <empty>
     {358, 0}, // 36: exception_especification ->  <empty>
     {350, 1}, // 37: ptr_operator ('*') ->  '*'
     {350, 1}, // 38: ptr_operator ('&') ->  '&'
     {359, 1}, // 39: declarator_id ->  identifier
     {359, 2}, // 40: declarator_id ('~') ->  '~' identifier
     {347, 1}, // 41: initializer ->  brace_or_equal_initializer
     {360, 2}, // 42: brace_or_equal_initializer ('=') ->  '=' initializer_clause
     {361, 1}, // 43: initializer_clause ->  expression
     {362, 1}, // 44: namespace_definition ->  named_namespace_definition
     {362, 1}, // 45: namespace_definition ->  unnamed_namespace_definition
     {363, 5}, // 46: named_namespace_definition (NAMESPACE) ->  NAMESPACE identifier '{' declaration_seq '}'
     {363, 6}, // 47: named_namespace_definition (INLINE) ->  INLINE NAMESPACE identifier '{' declaration_seq '}'
     {364, 4}, // 48: unnamed_namespace_definition (NAMESPACE) ->  NAMESPACE '{' declaration_seq '}'
     {364, 5}, // 49: unnamed_namespace_definition (INLINE) ->  INLINE NAMESPACE '{' declaration_seq '}'
     {365, 1}, // 50: type_specifier ->  trailing_type_specifier
     {365, 1}, // 51: type_specifier ->  class_specifier
     {366, 1}, // 52: trailing_type_specifier ->  simple_type_specifier
     {367, 1}, // 53: simple_type_specifier ->  type_name
     {368, 1}, // 54: type_name ->  identifier
     {369, 1}, // 55: access_specifier (PRIVATE) ->  PRIVATE
     {369, 1}, // 56: access_specifier (PROTECTED) ->  PROTECTED
     {369, 1}, // 57: access_specifier (PUBLIC) ->  PUBLIC
     {370, 4}, // 58: class_specifier ('{') ->  class_head '{' #0001 '}'
     {371, 0}, // 59: #0001 ->  <empty>
     {370, 5}, // 60: class_specifier ('{') ->  class_head '{' member_specification #0002 '}'
     {372, 0}, // 61: #0002 ->  <empty>
     {373, 1}, // 62: class_head ->  class_key
     {373, 2}, // 63: class_head ->  class_key base_clause
     {373, 2}, // 64: class_head ->  class_key class_head_name
     {373, 3}, // 65: class_head ->  class_key class_head_name base_clause
     {375, 1}, // 66: class_head_name ->  class_name
     {376, 2}, // 67: base_clause (':') ->  ':' base_specifier_list
     {377, 1}, // 68: base_specifier_list ->  base_specifier
     {377, 3}, // 69: base_specifier_list (',') ->  base_specifier_list ',' base_specifier
     {378, 1}, // 70: base_specifier ->  base_type_specifier
     {378, 2}, // 71: base_specifier (VIRTUAL) ->  VIRTUAL base_type_specifier
     {378, 2}, // 72: base_specifier ->  access_specifier base_type_specifier
     {378, 3}, // 73: base_specifier (VIRTUAL) ->  VIRTUAL access_specifier base_type_specifier
     {378, 3}, // 74: base_specifier (VIRTUAL) ->  access_specifier VIRTUAL base_type_specifier
     {379, 1}, // 75: base_type_specifier ->  class_name
     {380, 1}, // 76: class_name ->  identifier
     {374, 1}, // 77: class_key (CLASS) ->  CLASS
     {374, 1}, // 78: class_key (UNION) ->  UNION
     {374, 1}, // 79: class_key (STRUCT) ->  STRUCT
     {381, 1}, // 80: member_specification ->  member_declaration
     {381, 2}, // 81: member_specification ->  member_declaration member_specification
     {381, 2}, // 82: member_specification (':') ->  access_specifier ':'
     {381, 3}, // 83: member_specification (':') ->  access_specifier ':' member_specification
     {382, 2}, // 84: member_declaration (';') ->  member_declarator_list ';'
     {382, 2}, // 85: member_declaration (';') ->  decl_specifier_seq ';'
     {382, 3}, // 86: member_declaration (';') ->  decl_specifier_seq member_declarator_list ';'
     {383, 1}, // 87: member_declarator_list ->  member_declarator
     {383, 3}, // 88: member_declarator_list (',') ->  member_declarator_list ',' member_declarator
     {384, 1}, // 89: member_declarator ->  declarator
     {384, 2}, // 90: member_declarator ->  declarator pure_specifier
     {384, 2}, // 91: member_declarator ->  declarator brace_or_equal_initializer
     {384, 2}, // 92: member_declarator (':') ->  ':' constant_expression
     {384, 3}, // 93: member_declarator (':') ->  identifier ':' constant_expression
     {385, 2}, // 94: pure_specifier ('=') ->  '=' INTEGER_LITERAL
     {386, 1}, // 95: constant_expression ->  expression
     {352, 1}, // 96: expression ->  term
     {352, 2}, // 97: expression ->  expression term
     {387, 1}, // 98: term ->  literal
     {387, 1}, // 99: term ->  identifier
     {387, 1}, // 100: term ->  operand
     {387, 3}, // 101: term ('(') ->  '(' expression ')'
     {388, 1}, // 102: literal (STRING_LITERAL) ->  STRING_LITERAL
     {388, 1}, // 103: literal (CHARACTER_LITERAL) ->  CHARACTER_LITERAL
     {388, 1}, // 104: literal (INTEGER_LITERAL) ->  INTEGER_LITERAL
     {388, 1}, // 105: literal (HEXADECIMAL_LITERAL) ->  HEXADECIMAL_LITERAL
     {388, 1}, // 106: literal (OCTAL_LITERAL) ->  OCTAL_LITERAL
     {388, 1}, // 107: literal (FLOAT_LITERAL) ->  FLOAT_LITERAL
     {389, 1}, // 108: operand ('+') ->  '+'
     {389, 1}, // 109: operand ('-') ->  '-'
     {389, 1}, // 110: operand ('*') ->  '*'
     {389, 1}, // 111: operand ('/') ->  '/'
     {389, 1}, // 112: operand ('%') ->  '%'
     {389, 1}, // 113: operand ('^') ->  '^'
     {389, 1}, // 114: operand ('?') ->  '?'
     {389, 1}, // 115: operand (':') ->  ':'
     {390, 1}, // 116: identifier (IDENTIFIER) ->  IDENTIFIER
     {391, 1}, // 117: constructor_name (CONSTRUCTOR_NAME) ->  CONSTRUCTOR_NAME
     {392, 1}, // 118: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  3} },                   
    { {     338}, {  1} }, // input          
    { {     339}, {  2} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 39} },                                
    { {     340}, {  3} }, // declaration                 
    { {     341}, {  4} }, // block_declaration           
    { {     362}, {  5} }, // namespace_definition        
    { {     342}, {  6} }, // simple_declaration          
    { {     363}, {  7} }, // named_namespace_definition  
    { {     364}, {  8} }, // unnamed_namespace_definition
    { {      59}, {  9} }, // ';'                         
    { {     343}, { 10} }, // decl_specifier_seq          
    { {     345}, { 11} }, // init_declarator_list        
    { {     271}, { 12} }, // NAMESPACE                   
    { {     269}, { 13} }, // INLINE                      
    { {     365}, { 14} }, // type_specifier              
    { {     344}, { 15} }, // decl_specifier              
    { {     346}, { 16} }, // init_declarator             
    { {     366}, { 17} }, // trailing_type_specifier     
    { {     370}, { 18} }, // class_specifier             
    { {     268}, { 19} }, // FRIEND                      
    { {     286}, { 20} }, // TYPEDEF                     
    { {     348}, { 21} }, // declarator                  
    { {     367}, { 22} }, // simple_type_specifier       
    { {     373}, { 23} }, // class_head                  
    { {     349}, { 24} }, // ptr_declarator              
    { {     368}, { 25} }, // type_name                   
    { {     374}, { 26} }, // class_key                   
    { {     351}, { 27} }, // noptr_declarator            
    { {     350}, { 28} }, // ptr_operator                
    { {     390}, { 29} }, // identifier                  
    { {     261}, { 30} }, // CLASS                       
    { {     289}, { 31} }, // UNION                       
    { {     281}, { 32} }, // STRUCT                      
    { {     359}, { 33} }, // declarator_id               
    { {     391}, { 34} }, // constructor_name            
    { {      40}, { 35} }, // '('                         
    { {      42}, { 36} }, // '*'                         
    { {      38}, { 37} }, // '&'                         
    { {     257}, { 38} }, // IDENTIFIER                  
    { {     126}, { 39} }, // '~'                         
    { {     258}, { 40} }, // CONSTRUCTOR_NAME            
    { {       0}, { -1} },                                
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 17} },                        
    { {       345}, { 41} }, // init_declarator_list
    { {        59}, { 42} }, // ';'                 
    { {       346}, { 16} }, // init_declarator     
    { {       348}, { 21} }, // declarator          
    { {       349}, { 24} }, // ptr_declarator      
    { {       351}, { 27} }, // noptr_declarator    
    { {       350}, { 28} }, // ptr_operator        
    { {       359}, { 33} }, // declarator_id       
    { {       391}, { 34} }, // constructor_name    
    { {        40}, { 35} }, // '('                 
    { {        42}, { 36} }, // '*'                 
    { {        38}, { 37} }, // '&'                 
    { {       390}, { 43} }, // identifier          
    { {       126}, { 39} }, // '~'                 
    { {       258}, { 40} }, // CONSTRUCTOR_NAME    
    { {       257}, { 38} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 44} }, // ';'
    { {        44}, { 45} }, // ','
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       390}, { 46} }, // identifier
    { {       123}, { 47} }, // '{'       
    { {       257}, { 38} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       271}, { 48} }, // NAMESPACE
    { {         0}, {  0} },             
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, { 17} },                           
    { {       343}, { 49} }, // decl_specifier_seq     
    { {       365}, { 14} }, // type_specifier         
    { {       344}, { 15} }, // decl_specifier         
    { {       366}, { 17} }, // trailing_type_specifier
    { {       370}, { 18} }, // class_specifier        
    { {       268}, { 19} }, // FRIEND                 
    { {       286}, { 20} }, // TYPEDEF                
    { {       367}, { 22} }, // simple_type_specifier  
    { {       373}, { 23} }, // class_head             
    { {       368}, { 25} }, // type_name              
    { {       374}, { 26} }, // class_key              
    { {       390}, { 50} }, // identifier             
    { {       261}, { 30} }, // CLASS                  
    { {       289}, { 31} }, // UNION                  
    { {       281}, { 32} }, // STRUCT                 
    { {       257}, { 38} }, // IDENTIFIER             
    { {         0}, {  0} },                           
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_21[] =
{
    { { REQ_DEF}, {   4} },                              
    { {     347}, {  51} }, // initializer               
    { {     360}, {  52} }, // brace_or_equal_initializer
    { {      61}, {  53} }, // '='                       
    { {       0}, { -17} },                              
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 54} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_26[] =
{
    { { REQ_DEF}, {   7} },                   
    { {     376}, {  55} }, // base_clause    
    { {     375}, {  56} }, // class_head_name
    { {      58}, {  57} }, // ':'            
    { {     380}, {  58} }, // class_name     
    { {     390}, {  59} }, // identifier     
    { {     257}, {  38} }, // IDENTIFIER     
    { {       0}, { -62} },                   
};

SR__ s_27[] =
{
    { { REQ_DEF}, {   4} },                             
    { {     353}, {  60} }, // parameters_and_qualifiers
    { {      91}, {  61} }, // '['                      
    { {      40}, {  62} }, // '('                      
    { {       0}, { -20} },                             
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       349}, { 63} }, // ptr_declarator  
    { {       351}, { 27} }, // noptr_declarator
    { {       350}, { 28} }, // ptr_operator    
    { {       359}, { 33} }, // declarator_id   
    { {       391}, { 34} }, // constructor_name
    { {        40}, { 35} }, // '('             
    { {        42}, { 36} }, // '*'             
    { {        38}, { 37} }, // '&'             
    { {       390}, { 43} }, // identifier      
    { {       126}, { 39} }, // '~'             
    { {       258}, { 40} }, // CONSTRUCTOR_NAME
    { {       257}, { 38} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_29[] =
{
    { { REQ_DEF}, {   6} },                    
    { {     257}, { -54} }, // IDENTIFIER      
    { {     258}, { -54} }, // CONSTRUCTOR_NAME
    { {      42}, { -54} }, // '*'             
    { {      38}, { -54} }, // '&'             
    { {     126}, { -54} }, // '~'             
    { {       0}, { -39} },                    
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       349}, { 64} }, // ptr_declarator  
    { {       351}, { 27} }, // noptr_declarator
    { {       350}, { 28} }, // ptr_operator    
    { {       359}, { 33} }, // declarator_id   
    { {       391}, { 34} }, // constructor_name
    { {        40}, { 35} }, // '('             
    { {        42}, { 36} }, // '*'             
    { {        38}, { 37} }, // '&'             
    { {       390}, { 43} }, // identifier      
    { {       126}, { 39} }, // '~'             
    { {       258}, { 40} }, // CONSTRUCTOR_NAME
    { {       257}, { 38} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -116} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       390}, { 65} }, // identifier
    { {       257}, { 38} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_40[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -117} }, 
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 66} }, // ';'
    { {        44}, { 45} }, // ','
    { {         0}, {  0} },       
};

SR__ s_42[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 15} },                    
    { {       346}, { 67} }, // init_declarator 
    { {       348}, { 21} }, // declarator      
    { {       349}, { 24} }, // ptr_declarator  
    { {       351}, { 27} }, // noptr_declarator
    { {       350}, { 28} }, // ptr_operator    
    { {       359}, { 33} }, // declarator_id   
    { {       391}, { 34} }, // constructor_name
    { {        40}, { 35} }, // '('             
    { {        42}, { 36} }, // '*'             
    { {        38}, { 37} }, // '&'             
    { {       390}, { 43} }, // identifier      
    { {       126}, { 39} }, // '~'             
    { {       258}, { 40} }, // CONSTRUCTOR_NAME
    { {       257}, { 38} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 68} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_47[] =
{
    { { DEF_RED}, {  2} },                   
    { {     339}, { 69} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       390}, { 70} }, // identifier
    { {       123}, { 71} }, // '{'       
    { {       257}, { 38} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 23} },                       
    { {       361}, { 72} }, // initializer_clause 
    { {       352}, { 73} }, // expression         
    { {       387}, { 74} }, // term               
    { {       388}, { 75} }, // literal            
    { {       390}, { 76} }, // identifier         
    { {       389}, { 77} }, // operand            
    { {        40}, { 78} }, // '('                
    { {       295}, { 79} }, // STRING_LITERAL     
    { {       296}, { 80} }, // CHARACTER_LITERAL  
    { {       297}, { 81} }, // INTEGER_LITERAL    
    { {       298}, { 82} }, // HEXADECIMAL_LITERAL
    { {       299}, { 83} }, // OCTAL_LITERAL      
    { {       300}, { 84} }, // FLOAT_LITERAL      
    { {       257}, { 38} }, // IDENTIFIER         
    { {        43}, { 85} }, // '+'                
    { {        45}, { 86} }, // '-'                
    { {        42}, { 87} }, // '*'                
    { {        47}, { 88} }, // '/'                
    { {        37}, { 89} }, // '%'                
    { {        94}, { 90} }, // '^'                
    { {        63}, { 91} }, // '?'                
    { {        58}, { 92} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_54[] =
{
    { { REQ_DEF}, {  38} },                           
    { {     371}, {  93} }, // #0001                  
    { {     381}, {  94} }, // member_specification   
    { {     382}, {  95} }, // member_declaration     
    { {     369}, {  96} }, // access_specifier       
    { {     383}, {  97} }, // member_declarator_list 
    { {     343}, {  98} }, // decl_specifier_seq     
    { {     273}, {  99} }, // PRIVATE                
    { {     274}, { 100} }, // PROTECTED              
    { {     275}, { 101} }, // PUBLIC                 
    { {     384}, { 102} }, // member_declarator      
    { {     365}, {  14} }, // type_specifier         
    { {     344}, {  15} }, // decl_specifier         
    { {     348}, { 103} }, // declarator             
    { {      58}, { 104} }, // ':'                    
    { {     390}, { 105} }, // identifier             
    { {     366}, {  17} }, // trailing_type_specifier
    { {     370}, {  18} }, // class_specifier        
    { {     268}, {  19} }, // FRIEND                 
    { {     286}, {  20} }, // TYPEDEF                
    { {     349}, {  24} }, // ptr_declarator         
    { {     257}, {  38} }, // IDENTIFIER             
    { {     367}, {  22} }, // simple_type_specifier  
    { {     373}, {  23} }, // class_head             
    { {     351}, {  27} }, // noptr_declarator       
    { {     350}, {  28} }, // ptr_operator           
    { {     368}, {  25} }, // type_name              
    { {     374}, {  26} }, // class_key              
    { {     359}, {  33} }, // declarator_id          
    { {     391}, {  34} }, // constructor_name       
    { {      40}, {  35} }, // '('                    
    { {      42}, {  36} }, // '*'                    
    { {      38}, {  37} }, // '&'                    
    { {     261}, {  30} }, // CLASS                  
    { {     289}, {  31} }, // UNION                  
    { {     281}, {  32} }, // STRUCT                 
    { {     126}, {  39} }, // '~'                    
    { {     258}, {  40} }, // CONSTRUCTOR_NAME       
    { {       0}, { -59} },                           
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   3} },               
    { {     376}, { 106} }, // base_clause
    { {      58}, {  57} }, // ':'        
    { {       0}, { -64} },               
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  12} },                       
    { {       377}, { 107} }, // base_specifier_list
    { {       378}, { 108} }, // base_specifier     
    { {       379}, { 109} }, // base_type_specifier
    { {       292}, { 110} }, // VIRTUAL            
    { {       369}, { 111} }, // access_specifier   
    { {       380}, { 112} }, // class_name         
    { {       273}, {  99} }, // PRIVATE            
    { {       274}, { 100} }, // PROTECTED          
    { {       275}, { 101} }, // PUBLIC             
    { {       390}, {  59} }, // identifier         
    { {       257}, {  38} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  23} },                       
    { {       352}, { 113} }, // expression         
    { {        93}, { 114} }, // ']'                
    { {       387}, {  74} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       297}, {  81} }, // INTEGER_LITERAL    
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_62[] =
{
    { { REQ_DEF}, {  20} },                                
    { {     354}, { 115} }, // parameter_declaration_clause
    { {     355}, { 116} }, // parameter_declaration_list  
    { {     356}, { 117} }, // parameter_declaration       
    { {     343}, { 118} }, // decl_specifier_seq          
    { {     365}, {  14} }, // type_specifier              
    { {     344}, {  15} }, // decl_specifier              
    { {     366}, {  17} }, // trailing_type_specifier     
    { {     370}, {  18} }, // class_specifier             
    { {     268}, {  19} }, // FRIEND                      
    { {     286}, {  20} }, // TYPEDEF                     
    { {     367}, {  22} }, // simple_type_specifier       
    { {     373}, {  23} }, // class_head                  
    { {     368}, {  25} }, // type_name                   
    { {     374}, {  26} }, // class_key                   
    { {     390}, {  50} }, // identifier                  
    { {     261}, {  30} }, // CLASS                       
    { {     289}, {  31} }, // UNION                       
    { {     281}, {  32} }, // STRUCT                      
    { {     257}, {  38} }, // IDENTIFIER                  
    { {       0}, { -29} },                                
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 119} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   2} },                   
    { {     339}, { 120} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  40} },                                
    { {       125}, { 121} }, // '}'                         
    { {       340}, {   3} }, // declaration                 
    { {       341}, {   4} }, // block_declaration           
    { {       362}, {   5} }, // namespace_definition        
    { {       342}, {   6} }, // simple_declaration          
    { {       363}, {   7} }, // named_namespace_definition  
    { {       364}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       343}, {  10} }, // decl_specifier_seq          
    { {       345}, {  11} }, // init_declarator_list        
    { {       271}, {  12} }, // NAMESPACE                   
    { {       269}, {  13} }, // INLINE                      
    { {       365}, {  14} }, // type_specifier              
    { {       344}, {  15} }, // decl_specifier              
    { {       346}, {  16} }, // init_declarator             
    { {       366}, {  17} }, // trailing_type_specifier     
    { {       370}, {  18} }, // class_specifier             
    { {       268}, {  19} }, // FRIEND                      
    { {       286}, {  20} }, // TYPEDEF                     
    { {       348}, {  21} }, // declarator                  
    { {       367}, {  22} }, // simple_type_specifier       
    { {       373}, {  23} }, // class_head                  
    { {       349}, {  24} }, // ptr_declarator              
    { {       368}, {  25} }, // type_name                   
    { {       374}, {  26} }, // class_key                   
    { {       351}, {  27} }, // noptr_declarator            
    { {       350}, {  28} }, // ptr_operator                
    { {       390}, {  29} }, // identifier                  
    { {       261}, {  30} }, // CLASS                       
    { {       289}, {  31} }, // UNION                       
    { {       281}, {  32} }, // STRUCT                      
    { {       359}, {  33} }, // declarator_id               
    { {       391}, {  34} }, // constructor_name            
    { {        40}, {  35} }, // '('                         
    { {        42}, {  36} }, // '*'                         
    { {        38}, {  37} }, // '&'                         
    { {       257}, {  38} }, // IDENTIFIER                  
    { {       126}, {  39} }, // '~'                         
    { {       258}, {  40} }, // CONSTRUCTOR_NAME            
    { {         0}, {   0} },                                
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       123}, { 122} }, // '{'
    { {         0}, {   0} },       
};

SR__ s_71[] =
{
    { { DEF_RED}, {   2} },                   
    { {     339}, { 123} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_73[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     387}, { 124} }, // term               
    { {     388}, {  75} }, // literal            
    { {     390}, {  76} }, // identifier         
    { {     389}, {  77} }, // operand            
    { {      40}, {  78} }, // '('                
    { {     295}, {  79} }, // STRING_LITERAL     
    { {     296}, {  80} }, // CHARACTER_LITERAL  
    { {     297}, {  81} }, // INTEGER_LITERAL    
    { {     298}, {  82} }, // HEXADECIMAL_LITERAL
    { {     299}, {  83} }, // OCTAL_LITERAL      
    { {     300}, {  84} }, // FLOAT_LITERAL      
    { {     257}, {  38} }, // IDENTIFIER         
    { {      43}, {  85} }, // '+'                
    { {      45}, {  86} }, // '-'                
    { {      42}, {  87} }, // '*'                
    { {      47}, {  88} }, // '/'                
    { {      37}, {  89} }, // '%'                
    { {      94}, {  90} }, // '^'                
    { {      63}, {  91} }, // '?'                
    { {      58}, {  92} }, // ':'                
    { {       0}, { -43} },                       
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -96} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -98} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -99} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -100} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {       352}, { 125} }, // expression         
    { {       387}, {  74} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       297}, {  81} }, // INTEGER_LITERAL    
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_79[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -102} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -103} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -104} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -105} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -106} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -107} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -108} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -109} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -110} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -111} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -112} }, 
};

SR__ s_90[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -113} }, 
};

SR__ s_91[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -114} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -115} }, 
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       125}, { 126} }, // '}'
    { {         0}, {   0} },       
};

SR__ s_94[] =
{
    { { DEF_RED}, {   2} },         
    { {     372}, { 127} }, // #0002
    { {       0}, { -61} },         
};

SR__ s_95[] =
{
    { { REQ_DEF}, {  37} },                           
    { {     381}, { 128} }, // member_specification   
    { {     382}, {  95} }, // member_declaration     
    { {     369}, {  96} }, // access_specifier       
    { {     383}, {  97} }, // member_declarator_list 
    { {     343}, {  98} }, // decl_specifier_seq     
    { {     273}, {  99} }, // PRIVATE                
    { {     274}, { 100} }, // PROTECTED              
    { {     275}, { 101} }, // PUBLIC                 
    { {     384}, { 102} }, // member_declarator      
    { {     365}, {  14} }, // type_specifier         
    { {     344}, {  15} }, // decl_specifier         
    { {     348}, { 103} }, // declarator             
    { {      58}, { 104} }, // ':'                    
    { {     390}, { 105} }, // identifier             
    { {     366}, {  17} }, // trailing_type_specifier
    { {     370}, {  18} }, // class_specifier        
    { {     268}, {  19} }, // FRIEND                 
    { {     286}, {  20} }, // TYPEDEF                
    { {     349}, {  24} }, // ptr_declarator         
    { {     257}, {  38} }, // IDENTIFIER             
    { {     367}, {  22} }, // simple_type_specifier  
    { {     373}, {  23} }, // class_head             
    { {     351}, {  27} }, // noptr_declarator       
    { {     350}, {  28} }, // ptr_operator           
    { {     368}, {  25} }, // type_name              
    { {     374}, {  26} }, // class_key              
    { {     359}, {  33} }, // declarator_id          
    { {     391}, {  34} }, // constructor_name       
    { {      40}, {  35} }, // '('                    
    { {      42}, {  36} }, // '*'                    
    { {      38}, {  37} }, // '&'                    
    { {     261}, {  30} }, // CLASS                  
    { {     289}, {  31} }, // UNION                  
    { {     281}, {  32} }, // STRUCT                 
    { {     126}, {  39} }, // '~'                    
    { {     258}, {  40} }, // CONSTRUCTOR_NAME       
    { {       0}, { -80} },                           
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        58}, { 129} }, // ':'
    { {         0}, {   0} },       
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        59}, { 130} }, // ';'
    { {        44}, { 131} }, // ','
    { {         0}, {   0} },       
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {  18} },                          
    { {        59}, { 132} }, // ';'                   
    { {       383}, { 133} }, // member_declarator_list
    { {       384}, { 102} }, // member_declarator     
    { {       348}, { 103} }, // declarator            
    { {        58}, { 104} }, // ':'                   
    { {       390}, { 134} }, // identifier            
    { {       349}, {  24} }, // ptr_declarator        
    { {       257}, {  38} }, // IDENTIFIER            
    { {       351}, {  27} }, // noptr_declarator      
    { {       350}, {  28} }, // ptr_operator          
    { {       359}, {  33} }, // declarator_id         
    { {       391}, {  34} }, // constructor_name      
    { {        40}, {  35} }, // '('                   
    { {        42}, {  36} }, // '*'                   
    { {        38}, {  37} }, // '&'                   
    { {       126}, {  39} }, // '~'                   
    { {       258}, {  40} }, // CONSTRUCTOR_NAME      
    { {         0}, {   0} },                          
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   4} },                              
    { {     385}, { 135} }, // pure_specifier            
    { {     360}, { 136} }, // brace_or_equal_initializer
    { {      61}, { 137} }, // '='                       
    { {       0}, { -89} },                              
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {  23} },                       
    { {       386}, { 138} }, // constant_expression
    { {       352}, { 139} }, // expression         
    { {       387}, {  74} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       297}, {  81} }, // INTEGER_LITERAL    
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   4} },                    
    { {      58}, { 140} }, // ':'             
    { {     257}, { -54} }, // IDENTIFIER      
    { {     258}, { -54} }, // CONSTRUCTOR_NAME
    { {      42}, { -54} }, // '*'             
    { {      38}, { -54} }, // '&'             
    { {     126}, { -54} }, // '~'             
    { {       0}, { -39} },                    
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 141} }, // ','
    { {       0}, { -67} },       
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   9} },                       
    { {       379}, { 142} }, // base_type_specifier
    { {       369}, { 143} }, // access_specifier   
    { {       380}, { 112} }, // class_name         
    { {       273}, {  99} }, // PRIVATE            
    { {       274}, { 100} }, // PROTECTED          
    { {       275}, { 101} }, // PUBLIC             
    { {       390}, {  59} }, // identifier         
    { {       257}, {  38} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {   6} },                       
    { {       379}, { 144} }, // base_type_specifier
    { {       292}, { 145} }, // VIRTUAL            
    { {       380}, { 112} }, // class_name         
    { {       390}, {  59} }, // identifier         
    { {       257}, {  38} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {        93}, { 146} }, // ']'                
    { {       387}, { 124} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       297}, {  81} }, // INTEGER_LITERAL    
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 147} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_116[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 148} }, // ','
    { {       0}, { -30} },       
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_118[] =
{
    { { REQ_DEF}, {  14} },                    
    { {     348}, { 149} }, // declarator      
    { {     349}, {  24} }, // ptr_declarator  
    { {     351}, {  27} }, // noptr_declarator
    { {     350}, {  28} }, // ptr_operator    
    { {     359}, {  33} }, // declarator_id   
    { {     391}, {  34} }, // constructor_name
    { {      40}, {  35} }, // '('             
    { {      42}, {  36} }, // '*'             
    { {      38}, {  37} }, // '&'             
    { {     390}, {  43} }, // identifier      
    { {     126}, {  39} }, // '~'             
    { {     258}, {  40} }, // CONSTRUCTOR_NAME
    { {     257}, {  38} }, // IDENTIFIER      
    { {       0}, { -33} },                    
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  40} },                                
    { {       125}, { 150} }, // '}'                         
    { {       340}, {   3} }, // declaration                 
    { {       341}, {   4} }, // block_declaration           
    { {       362}, {   5} }, // namespace_definition        
    { {       342}, {   6} }, // simple_declaration          
    { {       363}, {   7} }, // named_namespace_definition  
    { {       364}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       343}, {  10} }, // decl_specifier_seq          
    { {       345}, {  11} }, // init_declarator_list        
    { {       271}, {  12} }, // NAMESPACE                   
    { {       269}, {  13} }, // INLINE                      
    { {       365}, {  14} }, // type_specifier              
    { {       344}, {  15} }, // decl_specifier              
    { {       346}, {  16} }, // init_declarator             
    { {       366}, {  17} }, // trailing_type_specifier     
    { {       370}, {  18} }, // class_specifier             
    { {       268}, {  19} }, // FRIEND                      
    { {       286}, {  20} }, // TYPEDEF                     
    { {       348}, {  21} }, // declarator                  
    { {       367}, {  22} }, // simple_type_specifier       
    { {       373}, {  23} }, // class_head                  
    { {       349}, {  24} }, // ptr_declarator              
    { {       368}, {  25} }, // type_name                   
    { {       374}, {  26} }, // class_key                   
    { {       351}, {  27} }, // noptr_declarator            
    { {       350}, {  28} }, // ptr_operator                
    { {       390}, {  29} }, // identifier                  
    { {       261}, {  30} }, // CLASS                       
    { {       289}, {  31} }, // UNION                       
    { {       281}, {  32} }, // STRUCT                      
    { {       359}, {  33} }, // declarator_id               
    { {       391}, {  34} }, // constructor_name            
    { {        40}, {  35} }, // '('                         
    { {        42}, {  36} }, // '*'                         
    { {        38}, {  37} }, // '&'                         
    { {       257}, {  38} }, // IDENTIFIER                  
    { {       126}, {  39} }, // '~'                         
    { {       258}, {  40} }, // CONSTRUCTOR_NAME            
    { {         0}, {   0} },                                
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_122[] =
{
    { { DEF_RED}, {   2} },                   
    { {     339}, { 151} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {  40} },                                
    { {       125}, { 152} }, // '}'                         
    { {       340}, {   3} }, // declaration                 
    { {       341}, {   4} }, // block_declaration           
    { {       362}, {   5} }, // namespace_definition        
    { {       342}, {   6} }, // simple_declaration          
    { {       363}, {   7} }, // named_namespace_definition  
    { {       364}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       343}, {  10} }, // decl_specifier_seq          
    { {       345}, {  11} }, // init_declarator_list        
    { {       271}, {  12} }, // NAMESPACE                   
    { {       269}, {  13} }, // INLINE                      
    { {       365}, {  14} }, // type_specifier              
    { {       344}, {  15} }, // decl_specifier              
    { {       346}, {  16} }, // init_declarator             
    { {       366}, {  17} }, // trailing_type_specifier     
    { {       370}, {  18} }, // class_specifier             
    { {       268}, {  19} }, // FRIEND                      
    { {       286}, {  20} }, // TYPEDEF                     
    { {       348}, {  21} }, // declarator                  
    { {       367}, {  22} }, // simple_type_specifier       
    { {       373}, {  23} }, // class_head                  
    { {       349}, {  24} }, // ptr_declarator              
    { {       368}, {  25} }, // type_name                   
    { {       374}, {  26} }, // class_key                   
    { {       351}, {  27} }, // noptr_declarator            
    { {       350}, {  28} }, // ptr_operator                
    { {       390}, {  29} }, // identifier                  
    { {       261}, {  30} }, // CLASS                       
    { {       289}, {  31} }, // UNION                       
    { {       281}, {  32} }, // STRUCT                      
    { {       359}, {  33} }, // declarator_id               
    { {       391}, {  34} }, // constructor_name            
    { {        40}, {  35} }, // '('                         
    { {        42}, {  36} }, // '*'                         
    { {        38}, {  37} }, // '&'                         
    { {       257}, {  38} }, // IDENTIFIER                  
    { {       126}, {  39} }, // '~'                         
    { {       258}, {  40} }, // CONSTRUCTOR_NAME            
    { {         0}, {   0} },                                
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -97} }, 
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {        41}, { 153} }, // ')'                
    { {       387}, { 124} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       297}, {  81} }, // INTEGER_LITERAL    
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       125}, { 154} }, // '}'
    { {         0}, {   0} },       
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR__ s_129[] =
{
    { { REQ_DEF}, {  37} },                           
    { {     381}, { 155} }, // member_specification   
    { {     382}, {  95} }, // member_declaration     
    { {     369}, {  96} }, // access_specifier       
    { {     383}, {  97} }, // member_declarator_list 
    { {     343}, {  98} }, // decl_specifier_seq     
    { {     273}, {  99} }, // PRIVATE                
    { {     274}, { 100} }, // PROTECTED              
    { {     275}, { 101} }, // PUBLIC                 
    { {     384}, { 102} }, // member_declarator      
    { {     365}, {  14} }, // type_specifier         
    { {     344}, {  15} }, // decl_specifier         
    { {     348}, { 103} }, // declarator             
    { {      58}, { 104} }, // ':'                    
    { {     390}, { 105} }, // identifier             
    { {     366}, {  17} }, // trailing_type_specifier
    { {     370}, {  18} }, // class_specifier        
    { {     268}, {  19} }, // FRIEND                 
    { {     286}, {  20} }, // TYPEDEF                
    { {     349}, {  24} }, // ptr_declarator         
    { {     257}, {  38} }, // IDENTIFIER             
    { {     367}, {  22} }, // simple_type_specifier  
    { {     373}, {  23} }, // class_head             
    { {     351}, {  27} }, // noptr_declarator       
    { {     350}, {  28} }, // ptr_operator           
    { {     368}, {  25} }, // type_name              
    { {     374}, {  26} }, // class_key              
    { {     359}, {  33} }, // declarator_id          
    { {     391}, {  34} }, // constructor_name       
    { {      40}, {  35} }, // '('                    
    { {      42}, {  36} }, // '*'                    
    { {      38}, {  37} }, // '&'                    
    { {     261}, {  30} }, // CLASS                  
    { {     289}, {  31} }, // UNION                  
    { {     281}, {  32} }, // STRUCT                 
    { {     126}, {  39} }, // '~'                    
    { {     258}, {  40} }, // CONSTRUCTOR_NAME       
    { {       0}, { -82} },                           
};

SR__ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {  16} },                     
    { {       384}, { 156} }, // member_declarator
    { {       348}, { 103} }, // declarator       
    { {        58}, { 104} }, // ':'              
    { {       390}, { 134} }, // identifier       
    { {       349}, {  24} }, // ptr_declarator   
    { {       257}, {  38} }, // IDENTIFIER       
    { {       351}, {  27} }, // noptr_declarator 
    { {       350}, {  28} }, // ptr_operator     
    { {       359}, {  33} }, // declarator_id    
    { {       391}, {  34} }, // constructor_name 
    { {        40}, {  35} }, // '('              
    { {        42}, {  36} }, // '*'              
    { {        38}, {  37} }, // '&'              
    { {       126}, {  39} }, // '~'              
    { {       258}, {  40} }, // CONSTRUCTOR_NAME 
    { {         0}, {   0} },                     
};

SR__ s_132[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        59}, { 157} }, // ';'
    { {        44}, { 131} }, // ','
    { {         0}, {   0} },       
};

SR__ s_134[] =
{
    { { REQ_DEF}, {   2} },       
    { {      58}, { 140} }, // ':'
    { {       0}, { -39} },       
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -90} }, 
};

SR__ s_136[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -91} }, 
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {  23} },                       
    { {       297}, { 158} }, // INTEGER_LITERAL    
    { {       361}, {  72} }, // initializer_clause 
    { {       352}, {  73} }, // expression         
    { {       387}, {  74} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -92} }, 
};

SR__ s_139[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     387}, { 124} }, // term               
    { {     388}, {  75} }, // literal            
    { {     390}, {  76} }, // identifier         
    { {     389}, {  77} }, // operand            
    { {      40}, {  78} }, // '('                
    { {     295}, {  79} }, // STRING_LITERAL     
    { {     296}, {  80} }, // CHARACTER_LITERAL  
    { {     297}, {  81} }, // INTEGER_LITERAL    
    { {     298}, {  82} }, // HEXADECIMAL_LITERAL
    { {     299}, {  83} }, // OCTAL_LITERAL      
    { {     300}, {  84} }, // FLOAT_LITERAL      
    { {     257}, {  38} }, // IDENTIFIER         
    { {      43}, {  85} }, // '+'                
    { {      45}, {  86} }, // '-'                
    { {      42}, {  87} }, // '*'                
    { {      47}, {  88} }, // '/'                
    { {      37}, {  89} }, // '%'                
    { {      94}, {  90} }, // '^'                
    { {      63}, {  91} }, // '?'                
    { {      58}, {  92} }, // ':'                
    { {       0}, { -95} },                       
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {  23} },                       
    { {       386}, { 159} }, // constant_expression
    { {       352}, { 139} }, // expression         
    { {       387}, {  74} }, // term               
    { {       388}, {  75} }, // literal            
    { {       390}, {  76} }, // identifier         
    { {       389}, {  77} }, // operand            
    { {        40}, {  78} }, // '('                
    { {       295}, {  79} }, // STRING_LITERAL     
    { {       296}, {  80} }, // CHARACTER_LITERAL  
    { {       297}, {  81} }, // INTEGER_LITERAL    
    { {       298}, {  82} }, // HEXADECIMAL_LITERAL
    { {       299}, {  83} }, // OCTAL_LITERAL      
    { {       300}, {  84} }, // FLOAT_LITERAL      
    { {       257}, {  38} }, // IDENTIFIER         
    { {        43}, {  85} }, // '+'                
    { {        45}, {  86} }, // '-'                
    { {        42}, {  87} }, // '*'                
    { {        47}, {  88} }, // '/'                
    { {        37}, {  89} }, // '%'                
    { {        94}, {  90} }, // '^'                
    { {        63}, {  91} }, // '?'                
    { {        58}, {  92} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_141[] =
{
    { { REQ_TOKEN}, {  11} },                       
    { {       378}, { 160} }, // base_specifier     
    { {       379}, { 109} }, // base_type_specifier
    { {       292}, { 110} }, // VIRTUAL            
    { {       369}, { 111} }, // access_specifier   
    { {       380}, { 112} }, // class_name         
    { {       273}, {  99} }, // PRIVATE            
    { {       274}, { 100} }, // PROTECTED          
    { {       275}, { 101} }, // PUBLIC             
    { {       390}, {  59} }, // identifier         
    { {       257}, {  38} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_142[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_143[] =
{
    { { REQ_TOKEN}, {   5} },                       
    { {       379}, { 161} }, // base_type_specifier
    { {       380}, { 112} }, // class_name         
    { {       390}, {  59} }, // identifier         
    { {       257}, {  38} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_145[] =
{
    { { REQ_TOKEN}, {   5} },                       
    { {       379}, { 162} }, // base_type_specifier
    { {       380}, { 112} }, // class_name         
    { {       390}, {  59} }, // identifier         
    { {       257}, {  38} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_146[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_147[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_148[] =
{
    { { REQ_TOKEN}, {  18} },                           
    { {       356}, { 163} }, // parameter_declaration  
    { {       343}, { 118} }, // decl_specifier_seq     
    { {       365}, {  14} }, // type_specifier         
    { {       344}, {  15} }, // decl_specifier         
    { {       366}, {  17} }, // trailing_type_specifier
    { {       370}, {  18} }, // class_specifier        
    { {       268}, {  19} }, // FRIEND                 
    { {       286}, {  20} }, // TYPEDEF                
    { {       367}, {  22} }, // simple_type_specifier  
    { {       373}, {  23} }, // class_head             
    { {       368}, {  25} }, // type_name              
    { {       374}, {  26} }, // class_key              
    { {       390}, {  50} }, // identifier             
    { {       261}, {  30} }, // CLASS                  
    { {       289}, {  31} }, // UNION                  
    { {       281}, {  32} }, // STRUCT                 
    { {       257}, {  38} }, // IDENTIFIER             
    { {         0}, {   0} },                           
};

SR__ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {  40} },                                
    { {       125}, { 164} }, // '}'                         
    { {       340}, {   3} }, // declaration                 
    { {       341}, {   4} }, // block_declaration           
    { {       362}, {   5} }, // namespace_definition        
    { {       342}, {   6} }, // simple_declaration          
    { {       363}, {   7} }, // named_namespace_definition  
    { {       364}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       343}, {  10} }, // decl_specifier_seq          
    { {       345}, {  11} }, // init_declarator_list        
    { {       271}, {  12} }, // NAMESPACE                   
    { {       269}, {  13} }, // INLINE                      
    { {       365}, {  14} }, // type_specifier              
    { {       344}, {  15} }, // decl_specifier              
    { {       346}, {  16} }, // init_declarator             
    { {       366}, {  17} }, // trailing_type_specifier     
    { {       370}, {  18} }, // class_specifier             
    { {       268}, {  19} }, // FRIEND                      
    { {       286}, {  20} }, // TYPEDEF                     
    { {       348}, {  21} }, // declarator                  
    { {       367}, {  22} }, // simple_type_specifier       
    { {       373}, {  23} }, // class_head                  
    { {       349}, {  24} }, // ptr_declarator              
    { {       368}, {  25} }, // type_name                   
    { {       374}, {  26} }, // class_key                   
    { {       351}, {  27} }, // noptr_declarator            
    { {       350}, {  28} }, // ptr_operator                
    { {       390}, {  29} }, // identifier                  
    { {       261}, {  30} }, // CLASS                       
    { {       289}, {  31} }, // UNION                       
    { {       281}, {  32} }, // STRUCT                      
    { {       359}, {  33} }, // declarator_id               
    { {       391}, {  34} }, // constructor_name            
    { {        40}, {  35} }, // '('                         
    { {        42}, {  36} }, // '*'                         
    { {        38}, {  37} }, // '&'                         
    { {       257}, {  38} }, // IDENTIFIER                  
    { {       126}, {  39} }, // '~'                         
    { {       258}, {  40} }, // CONSTRUCTOR_NAME            
    { {         0}, {   0} },                                
};

SR__ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_153[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -101} }, 
};

SR__ s_154[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR__ s_156[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -88} }, 
};

SR__ s_157[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR__ s_158[] =
{
    { { REQ_DEF}, {    3} },       
    { {      44}, {  -94} }, // ','
    { {      59}, {  -94} }, // ';'
    { {       0}, { -104} },       
};

SR__ s_159[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -93} }, 
};

SR__ s_160[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_161[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_162[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_163[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_164[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,  s_161,  s_162,  s_163,  s_164,
};

} // anonymous namespace ends


// $insert namespace-open
namespace opwig
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

MDParserBase::MDParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void MDParser::print__()
{
// $insert print
}

void MDParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void MDParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void MDParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void MDParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void MDParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t MDParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void MDParser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 4 "grammar/toplevel_rules.gr"
        {
         for (auto it: *d_vsp__[0].data<Tag__::DeclarationSeq>())
         if (!(it) (global_namespace_))
         throw md::SemanticError("Namespace action failed (global)", __FILE__, __LINE__);
         }
        break;

        case 2:
#line 12 "grammar/toplevel_rules.gr"
        {
         d_val__.get<Tag__::DeclarationSeq>() = std::shared_ptr<ScopeActionList>(new ScopeActionList);
         }
        break;

        case 3:
#line 16 "grammar/toplevel_rules.gr"
        {
         (d_vsp__[-1].data<Tag__::DeclarationSeq>())->push_back(d_vsp__[0].data<Tag__::Declaration>());
         d_val__.get<Tag__::DeclarationSeq>() = d_vsp__[-1].data<Tag__::DeclarationSeq>();
         }
        break;

        case 4:
#line 23 "grammar/toplevel_rules.gr"
        {
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 5:
#line 27 "grammar/toplevel_rules.gr"
        { 
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 6:
#line 4 "grammar/declaration_rules.gr"
        { d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>(); }
        break;

        case 8:
#line 10 "grammar/declaration_rules.gr"
        {
         d_val__.get<Tag__::Declaration>() = parser::JoinDeclarations(d_vsp__[-2].data<Tag__::Type>(), d_vsp__[-1].data<Tag__::DeclaratorSeq>());
         }
        break;

        case 9:
#line 14 "grammar/declaration_rules.gr"
        {
         d_val__.get<Tag__::Declaration>() = parser::AddTypeToScope(d_vsp__[-1].data<Tag__::Type>());
         }
        break;

        case 11:
#line 22 "grammar/declaration_rules.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 12:
#line 24 "grammar/declaration_rules.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 15:
#line 4 "grammar/declarator_rules.gr"
        {
         d_val__.get<Tag__::DeclaratorSeq>() = std::shared_ptr<parser::DeclaratorList>(new parser::DeclaratorList);
         (d_val__.get<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         }
        break;

        case 16:
#line 9 "grammar/declarator_rules.gr"
        {
         (d_vsp__[-2].data<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         d_val__.get<Tag__::DeclaratorSeq>() = d_vsp__[-2].data<Tag__::DeclaratorSeq>();
         }
        break;

        case 17:
#line 16 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 18:
#line 18 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 19:
#line 22 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 20:
#line 26 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 21:
#line 28 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 22:
#line 32 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = parser::Declarator(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 23:
#line 34 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = parser::Declarator(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 24:
#line 36 "grammar/declarator_rules.gr"
        {
         d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>();
         (d_val__.get<Tag__::Declarator>()).set_parameters(d_vsp__[0].data<Tag__::ParameterSeq>());
         }
        break;

        case 25:
#line 41 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-3].data<Tag__::Declarator>(); }
        break;

        case 26:
#line 43 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-2].data<Tag__::Declarator>(); }
        break;

        case 27:
#line 45 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 28:
#line 49 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-1].data<Tag__::ParameterSeq>(); }
        break;

        case 29:
#line 59 "grammar/declarator_rules.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = std::shared_ptr<md::ParameterList>(new md::ParameterList);
         }
        break;

        case 30:
#line 63 "grammar/declarator_rules.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = d_vsp__[0].data<Tag__::ParameterSeq>();
         }
        break;

        case 31:
#line 69 "grammar/declarator_rules.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = std::shared_ptr<md::ParameterList>(new md::ParameterList);
         (d_val__.get<Tag__::ParameterSeq>())->push_back(d_vsp__[0].data<Tag__::Parameter>());
         }
        break;

        case 32:
#line 74 "grammar/declarator_rules.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-2].data<Tag__::ParameterSeq>();
         (d_val__.get<Tag__::ParameterSeq>())->push_back(d_vsp__[0].data<Tag__::Parameter>());
         }
        break;

        case 33:
#line 81 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Parameter>() = md::Parameter((d_vsp__[0].data<Tag__::Type>())(md::Ptr<md::Scope>()), ""); }
        break;

        case 34:
#line 83 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::Parameter>() = md::Parameter((d_vsp__[-1].data<Tag__::Type>())(md::Ptr<md::Scope>()), (d_vsp__[0].data<Tag__::Declarator>()).name()); }
        break;

        case 35:
#line 87 "grammar/declarator_rules.gr"
        {}
        break;

        case 36:
#line 91 "grammar/declarator_rules.gr"
        {}
        break;

        case 39:
#line 101 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 40:
#line 103 "grammar/declarator_rules.gr"
        { d_val__.get<Tag__::String>() = "~"+d_vsp__[0].data<Tag__::String>(); }
        break;

        case 44:
#line 4 "grammar/namespace_rules.gr"
        {
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 45:
#line 8 "grammar/namespace_rules.gr"
        {
         d_val__.get<Tag__::Declaration>() = [] (md::Ptr<md::Scope> current_namespace) -> bool { return true; };
         }
        break;

        case 46:
#line 14 "grammar/namespace_rules.gr"
        {
         using md::Namespace;
         using md::Ptr;
         std::string name = d_vsp__[-3].data<Tag__::String>();
         Ptr<Namespace> new_namespace = Namespace::Create(name);
         for (auto it: *d_vsp__[-1].data<Tag__::DeclarationSeq>())
         if (!(it) (new_namespace))
         throw md::SemanticError("Namespace action failed (new)", __FILE__, __LINE__);
         d_val__.get<Tag__::Declaration>() = [name,new_namespace] (Ptr<md::Scope> current_namespace) -> bool {
         return current_namespace->AddNestedNamespace(name, new_namespace);
         };
         }
        break;

        case 50:
#line 4 "grammar/type_rules.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 51:
#line 6 "grammar/type_rules.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 52:
#line 10 "grammar/type_rules.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 53:
#line 14 "grammar/type_rules.gr"
        { 
         std::string name = d_vsp__[0].data<Tag__::String>();
         d_val__.get<Tag__::Type>() = [name] (md::Ptr<md::Scope> current_namespace) -> std::string {
         return name;
         }; 
         }
        break;

        case 54:
#line 23 "grammar/type_rules.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 55:
#line 27 "grammar/type_rules.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = md::AccessSpecifier::PRIVATE; }
        break;

        case 56:
#line 29 "grammar/type_rules.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = md::AccessSpecifier::PROTECTED; }
        break;

        case 57:
#line 31 "grammar/type_rules.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = md::AccessSpecifier::PUBLIC; }
        break;

        case 58:
#line 7 "grammar/class_rules.gr"
        {
         md::Ptr<md::Class> classObj = d_vsp__[-3].data<Tag__::Class>();
         d_val__.get<Tag__::Type>() = [classObj] (md::Ptr<md::Scope> current_scope) -> std::string {
         if (current_scope->AddNestedClass(classObj->name(), classObj))
         return classObj->name();
         throw md::SemanticError("Non-anonymous class cannot have empty name!", __FILE__, __LINE__);
         };
         }
        break;

        case 59:
#line 4 "grammar/class_rules.gr"
        d_val__ = d_vsp__[-1];
        {
         d_scanner.ChangeScope(nullptr);
         std::cout << "Reseted scanner scope" << std::endl;
         }
        break;

        case 60:
#line 19 "grammar/class_rules.gr"
        {
         md::Ptr<md::Class> classObj = d_vsp__[-4].data<Tag__::Class>();
         for (auto it: *d_vsp__[-2].data<Tag__::DeclarationSeq>())
         if (!(it)(classObj))
         throw md::SemanticError("Error executing ScopeAction - member for class", __FILE__, __LINE__);
         d_val__.get<Tag__::Type>() = [classObj] (md::Ptr<md::Scope> current_scope) -> std::string {
         if (current_scope->AddNestedClass(classObj->name(), classObj))
         return classObj->name();
         throw md::SemanticError("Non-anonymous class cannot have empty name!", __FILE__, __LINE__);
         };
         }
        break;

        case 61:
#line 16 "grammar/class_rules.gr"
        d_val__ = d_vsp__[-2];
        {
         d_scanner.ChangeScope(nullptr);
         std::cout << "Reseted scanner scope" << std::endl;
         }
        break;

        case 62:
#line 33 "grammar/class_rules.gr"
        {
         d_val__.get<Tag__::Class>() = md::Class::Create("", BaseSpecifierList());
         d_scanner.ChangeScope(d_val__.get<Tag__::Class>());
         std::cout << "Changed scanner scope to: " << (d_val__.get<Tag__::Class>())->name() << std::endl;
         }
        break;

        case 63:
#line 39 "grammar/class_rules.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create("", *d_vsp__[0].data<Tag__::BaseSpecifierSeq>()); }
        break;

        case 64:
#line 41 "grammar/class_rules.gr"
        {
         d_val__.get<Tag__::Class>() = md::Class::Create(d_vsp__[0].data<Tag__::String>(), BaseSpecifierList());
         d_scanner.ChangeScope(d_val__.get<Tag__::Class>());
         std::cout << "Changed scanner scope to: " << (d_val__.get<Tag__::Class>())->name() << std::endl;
         }
        break;

        case 65:
#line 47 "grammar/class_rules.gr"
        {
         d_val__.get<Tag__::Class>() = md::Class::Create(d_vsp__[-1].data<Tag__::String>(), *d_vsp__[0].data<Tag__::BaseSpecifierSeq>());
         d_scanner.ChangeScope(d_val__.get<Tag__::Class>());
         std::cout << "Changed scanner scope to: " << (d_val__.get<Tag__::Class>())->name() << std::endl;
         }
        break;

        case 66:
#line 55 "grammar/class_rules.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 67:
#line 59 "grammar/class_rules.gr"
        { d_val__.get<Tag__::BaseSpecifierSeq>() = d_vsp__[0].data<Tag__::BaseSpecifierSeq>(); }
        break;

        case 68:
#line 63 "grammar/class_rules.gr"
        {
         d_val__.get<Tag__::BaseSpecifierSeq>() = std::shared_ptr<BaseSpecifierList>(new BaseSpecifierList);
         (d_val__.get<Tag__::BaseSpecifierSeq>())->push_back(d_vsp__[0].data<Tag__::BaseSpecifier>());
         }
        break;

        case 69:
#line 68 "grammar/class_rules.gr"
        {
         (d_vsp__[-2].data<Tag__::BaseSpecifierSeq>())->push_back(d_vsp__[0].data<Tag__::BaseSpecifier>());
         d_val__.get<Tag__::BaseSpecifierSeq>() = d_vsp__[-2].data<Tag__::BaseSpecifierSeq>();
         }
        break;

        case 70:
#line 75 "grammar/class_rules.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 71:
#line 77 "grammar/class_rules.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true); }
        break;

        case 72:
#line 79 "grammar/class_rules.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), d_vsp__[-1].data<Tag__::AccessSpecifier>()); }
        break;

        case 73:
#line 81 "grammar/class_rules.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true, d_vsp__[-1].data<Tag__::AccessSpecifier>()); }
        break;

        case 74:
#line 83 "grammar/class_rules.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true, d_vsp__[-2].data<Tag__::AccessSpecifier>()); }
        break;

        case 75:
#line 87 "grammar/class_rules.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 76:
#line 91 "grammar/class_rules.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 80:
#line 4 "grammar/member_rules.gr"
        {
         d_val__.get<Tag__::DeclarationSeq>() = std::shared_ptr<ScopeActionList>(new ScopeActionList);
         (d_val__.get<Tag__::DeclarationSeq>())->push_back(d_vsp__[0].data<Tag__::Declaration>());
         }
        break;

        case 81:
#line 9 "grammar/member_rules.gr"
        {
         (d_vsp__[0].data<Tag__::DeclarationSeq>())->push_front(d_vsp__[-1].data<Tag__::Declaration>());
         d_val__.get<Tag__::DeclarationSeq>() = d_vsp__[0].data<Tag__::DeclarationSeq>();
         }
        break;

        case 82:
#line 14 "grammar/member_rules.gr"
        {
         d_val__.get<Tag__::DeclarationSeq>() = std::shared_ptr<ScopeActionList>(new ScopeActionList);
         md::AccessSpecifier access = d_vsp__[-1].data<Tag__::AccessSpecifier>();
         ScopeAction action = [access] (md::Ptr<md::Scope> current_scope) -> bool {
         current_scope->SetAccessSpecifier(access);
         return true;
         };
         (d_val__.get<Tag__::DeclarationSeq>())->push_back(action);
         }
        break;

        case 83:
#line 24 "grammar/member_rules.gr"
        {
         md::AccessSpecifier access = d_vsp__[-2].data<Tag__::AccessSpecifier>();
         ScopeAction action = [access] (md::Ptr<md::Scope> current_scope) -> bool {
         current_scope->SetAccessSpecifier(access);
         return true;
         };
         (d_vsp__[0].data<Tag__::DeclarationSeq>())->push_front(action);
         d_val__.get<Tag__::DeclarationSeq>() = d_vsp__[0].data<Tag__::DeclarationSeq>();
         }
        break;

        case 84:
#line 36 "grammar/member_rules.gr"
        {
         std::cout << "Joining declarations" << std::endl;
         TypeAction action = [] (md::Ptr<md::Scope> current_scope) -> std::string { return ""; };
         d_val__.get<Tag__::Declaration>() = parser::JoinDeclarations(action, d_vsp__[-1].data<Tag__::DeclaratorSeq>());
         }
        break;

        case 85:
#line 42 "grammar/member_rules.gr"
        {
         std::cout << "Adding type to scope" << std::endl;
         d_val__.get<Tag__::Declaration>() = parser::AddTypeToScope(d_vsp__[-1].data<Tag__::Type>());
         }
        break;

        case 86:
#line 47 "grammar/member_rules.gr"
        {
         std::cout << "Joining declarations with return" << std::endl;
         d_val__.get<Tag__::Declaration>() = parser::JoinDeclarations(d_vsp__[-2].data<Tag__::Type>(), d_vsp__[-1].data<Tag__::DeclaratorSeq>());
         }
        break;

        case 87:
#line 55 "grammar/member_rules.gr"
        {
         d_val__.get<Tag__::DeclaratorSeq>() = std::shared_ptr<parser::DeclaratorList>(new parser::DeclaratorList);
         (d_val__.get<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         }
        break;

        case 88:
#line 60 "grammar/member_rules.gr"
        {
         (d_vsp__[-2].data<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         d_val__.get<Tag__::DeclaratorSeq>() = d_vsp__[-2].data<Tag__::DeclaratorSeq>();
         }
        break;

        case 89:
#line 67 "grammar/member_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 90:
#line 69 "grammar/member_rules.gr"
        {
         (d_vsp__[-1].data<Tag__::Declarator>()).set_pure(true);
         d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>();
         }
        break;

        case 91:
#line 74 "grammar/member_rules.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 94:
#line 82 "grammar/member_rules.gr"
        {
         if (d_vsp__[0] != 0)
         throw md::SemanticError("Errouneous pure-specifier (should be '= 0' )", __FILE__, __LINE__);
         }
        break;

        case 116:
#line 4 "grammar/identifier_rules.gr"
        {
         d_val__.get<Tag__::String>() = d_scanner.matched();
         }
        break;

        case 117:
#line 10 "grammar/identifier_rules.gr"
        {
         d_val__.get<Tag__::String>() = d_scanner.matched();
         }
        break;

    }
}

inline void MDParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void MDParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int MDParser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void MDParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int MDParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}


// $insert namespace-close
}


