// Generated by Bisonc++ V4.01.00 on Mon, 08 Apr 2013 23:01:03 -0300

// $insert class.ih
#include "mdparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {332, 1}, // 1: input ->  declaration_seq
     {333, 0}, // 2: declaration_seq ->  <empty>
     {333, 2}, // 3: declaration_seq ->  declaration_seq declaration
     {334, 1}, // 4: declaration ->  block_declaration
     {334, 1}, // 5: declaration ->  namespace_definition
     {335, 1}, // 6: block_declaration ->  simple_declaration
     {336, 1}, // 7: simple_declaration (';') ->  ';'
     {336, 3}, // 8: simple_declaration (';') ->  decl_specifier_seq init_declarator_list ';'
     {336, 2}, // 9: simple_declaration (';') ->  decl_specifier_seq ';'
     {336, 2}, // 10: simple_declaration (';') ->  init_declarator_list ';'
     {337, 1}, // 11: decl_specifier_seq ->  type_specifier
     {337, 2}, // 12: decl_specifier_seq ->  decl_specifier decl_specifier_seq
     {338, 1}, // 13: decl_specifier (FRIEND) ->  FRIEND
     {338, 1}, // 14: decl_specifier (TYPEDEF) ->  TYPEDEF
     {339, 1}, // 15: init_declarator_list ->  init_declarator
     {339, 3}, // 16: init_declarator_list (',') ->  init_declarator_list ',' init_declarator
     {340, 1}, // 17: init_declarator ->  declarator
     {340, 2}, // 18: init_declarator ->  declarator initializer
     {342, 1}, // 19: declarator ->  ptr_declarator
     {343, 1}, // 20: ptr_declarator ->  noptr_declarator
     {343, 2}, // 21: ptr_declarator ->  ptr_operator ptr_declarator
     {345, 1}, // 22: noptr_declarator ->  declarator_id
     {345, 2}, // 23: noptr_declarator ->  noptr_declarator parameters_and_qualifiers
     {345, 4}, // 24: noptr_declarator ('[') ->  noptr_declarator '[' expression ']'
     {345, 3}, // 25: noptr_declarator ('[') ->  noptr_declarator '[' ']'
     {345, 3}, // 26: noptr_declarator ('(') ->  '(' ptr_declarator ')'
     {347, 3}, // 27: parameters_and_qualifiers ('(') ->  '(' parameter_declaration_clause ')'
     {348, 0}, // 28: parameter_declaration_clause ->  <empty>
     {348, 1}, // 29: parameter_declaration_clause ->  parameter_declaration_list
     {349, 1}, // 30: parameter_declaration_list ->  parameter_declaration
     {349, 3}, // 31: parameter_declaration_list (',') ->  parameter_declaration_list ',' parameter_declaration
     {350, 1}, // 32: parameter_declaration ->  decl_specifier_seq
     {350, 2}, // 33: parameter_declaration ->  decl_specifier_seq declarator
     {351, 0}, // 34: cv_qualifier_seq ->  <empty>
     {352, 0}, // 35: exception_especification ->  <empty>
     {344, 1}, // 36: ptr_operator ('*') ->  '*'
     {344, 1}, // 37: ptr_operator ('&') ->  '&'
     {353, 1}, // 38: declarator_id ->  identifier
     {341, 1}, // 39: initializer ->  brace_or_equal_initializer
     {354, 2}, // 40: brace_or_equal_initializer ('=') ->  '=' initializer_clause
     {355, 1}, // 41: initializer_clause ->  expression
     {356, 1}, // 42: namespace_definition ->  named_namespace_definition
     {356, 1}, // 43: namespace_definition ->  unnamed_namespace_definition
     {357, 5}, // 44: named_namespace_definition (NAMESPACE) ->  NAMESPACE identifier '{' declaration_seq '}'
     {357, 6}, // 45: named_namespace_definition (INLINE) ->  INLINE NAMESPACE identifier '{' declaration_seq '}'
     {358, 4}, // 46: unnamed_namespace_definition (NAMESPACE) ->  NAMESPACE '{' declaration_seq '}'
     {358, 5}, // 47: unnamed_namespace_definition (INLINE) ->  INLINE NAMESPACE '{' declaration_seq '}'
     {359, 1}, // 48: type_specifier ->  trailing_type_specifier
     {359, 1}, // 49: type_specifier ->  class_specifier
     {360, 1}, // 50: trailing_type_specifier ->  simple_type_specifier
     {361, 1}, // 51: simple_type_specifier ->  type_name
     {362, 1}, // 52: type_name ->  identifier
     {363, 3}, // 53: class_specifier ('{') ->  class_head '{' '}'
     {364, 1}, // 54: class_head ->  class_key
     {364, 2}, // 55: class_head ->  class_key base_clause
     {364, 2}, // 56: class_head ->  class_key class_head_name
     {364, 3}, // 57: class_head ->  class_key class_head_name base_clause
     {366, 1}, // 58: class_head_name ->  class_name
     {367, 2}, // 59: base_clause (':') ->  ':' base_specifier_list
     {368, 1}, // 60: base_specifier_list ->  base_specifier
     {368, 3}, // 61: base_specifier_list (',') ->  base_specifier_list ',' base_specifier
     {369, 1}, // 62: base_specifier ->  base_type_specifier
     {369, 2}, // 63: base_specifier (VIRTUAL) ->  VIRTUAL base_type_specifier
     {369, 2}, // 64: base_specifier ->  access_specifier base_type_specifier
     {369, 3}, // 65: base_specifier (VIRTUAL) ->  VIRTUAL access_specifier base_type_specifier
     {369, 3}, // 66: base_specifier (VIRTUAL) ->  access_specifier VIRTUAL base_type_specifier
     {370, 1}, // 67: base_type_specifier ->  class_name
     {371, 1}, // 68: access_specifier (PRIVATE) ->  PRIVATE
     {371, 1}, // 69: access_specifier (PROTECTED) ->  PROTECTED
     {371, 1}, // 70: access_specifier (PUBLIC) ->  PUBLIC
     {372, 1}, // 71: class_name ->  identifier
     {365, 1}, // 72: class_key (CLASS) ->  CLASS
     {365, 1}, // 73: class_key (UNION) ->  UNION
     {365, 1}, // 74: class_key (STRUCT) ->  STRUCT
     {346, 1}, // 75: expression ->  term
     {346, 2}, // 76: expression ->  expression term
     {373, 1}, // 77: term ->  literal
     {373, 1}, // 78: term ->  identifier
     {373, 1}, // 79: term ->  operand
     {373, 3}, // 80: term ('(') ->  '(' expression ')'
     {374, 1}, // 81: literal (STRING_LITERAL) ->  STRING_LITERAL
     {374, 1}, // 82: literal (CHARACTER_LITERAL) ->  CHARACTER_LITERAL
     {374, 1}, // 83: literal (INTEGER_LITERAL) ->  INTEGER_LITERAL
     {374, 1}, // 84: literal (HEXADECIMAL_LITERAL) ->  HEXADECIMAL_LITERAL
     {374, 1}, // 85: literal (OCTAL_LITERAL) ->  OCTAL_LITERAL
     {374, 1}, // 86: literal (FLOAT_LITERAL) ->  FLOAT_LITERAL
     {375, 1}, // 87: operand ('+') ->  '+'
     {375, 1}, // 88: operand ('-') ->  '-'
     {375, 1}, // 89: operand ('*') ->  '*'
     {375, 1}, // 90: operand ('/') ->  '/'
     {375, 1}, // 91: operand ('%') ->  '%'
     {375, 1}, // 92: operand ('^') ->  '^'
     {375, 1}, // 93: operand ('?') ->  '?'
     {375, 1}, // 94: operand (':') ->  ':'
     {376, 1}, // 95: identifier (IDENTIFIER) ->  IDENTIFIER
     {377, 1}, // 96: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  3} },                   
    { {     332}, {  1} }, // input          
    { {     333}, {  2} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 36} },                                
    { {     334}, {  3} }, // declaration                 
    { {     335}, {  4} }, // block_declaration           
    { {     356}, {  5} }, // namespace_definition        
    { {     336}, {  6} }, // simple_declaration          
    { {     357}, {  7} }, // named_namespace_definition  
    { {     358}, {  8} }, // unnamed_namespace_definition
    { {      59}, {  9} }, // ';'                         
    { {     337}, { 10} }, // decl_specifier_seq          
    { {     339}, { 11} }, // init_declarator_list        
    { {     270}, { 12} }, // NAMESPACE                   
    { {     268}, { 13} }, // INLINE                      
    { {     359}, { 14} }, // type_specifier              
    { {     338}, { 15} }, // decl_specifier              
    { {     340}, { 16} }, // init_declarator             
    { {     360}, { 17} }, // trailing_type_specifier     
    { {     363}, { 18} }, // class_specifier             
    { {     267}, { 19} }, // FRIEND                      
    { {     285}, { 20} }, // TYPEDEF                     
    { {     342}, { 21} }, // declarator                  
    { {     361}, { 22} }, // simple_type_specifier       
    { {     364}, { 23} }, // class_head                  
    { {     343}, { 24} }, // ptr_declarator              
    { {     362}, { 25} }, // type_name                   
    { {     365}, { 26} }, // class_key                   
    { {     345}, { 27} }, // noptr_declarator            
    { {     344}, { 28} }, // ptr_operator                
    { {     376}, { 29} }, // identifier                  
    { {     260}, { 30} }, // CLASS                       
    { {     288}, { 31} }, // UNION                       
    { {     280}, { 32} }, // STRUCT                      
    { {     353}, { 33} }, // declarator_id               
    { {      40}, { 34} }, // '('                         
    { {      42}, { 35} }, // '*'                         
    { {      38}, { 36} }, // '&'                         
    { {     257}, { 37} }, // IDENTIFIER                  
    { {       0}, { -1} },                                
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       339}, { 38} }, // init_declarator_list
    { {        59}, { 39} }, // ';'                 
    { {       340}, { 16} }, // init_declarator     
    { {       342}, { 21} }, // declarator          
    { {       343}, { 24} }, // ptr_declarator      
    { {       345}, { 27} }, // noptr_declarator    
    { {       344}, { 28} }, // ptr_operator        
    { {       353}, { 33} }, // declarator_id       
    { {        40}, { 34} }, // '('                 
    { {        42}, { 35} }, // '*'                 
    { {        38}, { 36} }, // '&'                 
    { {       376}, { 40} }, // identifier          
    { {       257}, { 37} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 41} }, // ';'
    { {        44}, { 42} }, // ','
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       376}, { 43} }, // identifier
    { {       123}, { 44} }, // '{'       
    { {       257}, { 37} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       270}, { 45} }, // NAMESPACE
    { {         0}, {  0} },             
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, { 17} },                           
    { {       337}, { 46} }, // decl_specifier_seq     
    { {       359}, { 14} }, // type_specifier         
    { {       338}, { 15} }, // decl_specifier         
    { {       360}, { 17} }, // trailing_type_specifier
    { {       363}, { 18} }, // class_specifier        
    { {       267}, { 19} }, // FRIEND                 
    { {       285}, { 20} }, // TYPEDEF                
    { {       361}, { 22} }, // simple_type_specifier  
    { {       364}, { 23} }, // class_head             
    { {       362}, { 25} }, // type_name              
    { {       365}, { 26} }, // class_key              
    { {       376}, { 47} }, // identifier             
    { {       260}, { 30} }, // CLASS                  
    { {       288}, { 31} }, // UNION                  
    { {       280}, { 32} }, // STRUCT                 
    { {       257}, { 37} }, // IDENTIFIER             
    { {         0}, {  0} },                           
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_21[] =
{
    { { REQ_DEF}, {   4} },                              
    { {     341}, {  48} }, // initializer               
    { {     354}, {  49} }, // brace_or_equal_initializer
    { {      61}, {  50} }, // '='                       
    { {       0}, { -17} },                              
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 51} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_26[] =
{
    { { REQ_DEF}, {   7} },                   
    { {     367}, {  52} }, // base_clause    
    { {     366}, {  53} }, // class_head_name
    { {      58}, {  54} }, // ':'            
    { {     372}, {  55} }, // class_name     
    { {     376}, {  56} }, // identifier     
    { {     257}, {  37} }, // IDENTIFIER     
    { {       0}, { -54} },                   
};

SR__ s_27[] =
{
    { { REQ_DEF}, {   4} },                             
    { {     347}, {  57} }, // parameters_and_qualifiers
    { {      91}, {  58} }, // '['                      
    { {      40}, {  59} }, // '('                      
    { {       0}, { -20} },                             
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       343}, { 60} }, // ptr_declarator  
    { {       345}, { 27} }, // noptr_declarator
    { {       344}, { 28} }, // ptr_operator    
    { {       353}, { 33} }, // declarator_id   
    { {        40}, { 34} }, // '('             
    { {        42}, { 35} }, // '*'             
    { {        38}, { 36} }, // '&'             
    { {       376}, { 40} }, // identifier      
    { {       257}, { 37} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_29[] =
{
    { { REQ_DEF}, {   4} },              
    { {     257}, { -52} }, // IDENTIFIER
    { {      42}, { -52} }, // '*'       
    { {      38}, { -52} }, // '&'       
    { {       0}, { -38} },              
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       343}, { 61} }, // ptr_declarator  
    { {       345}, { 27} }, // noptr_declarator
    { {       344}, { 28} }, // ptr_operator    
    { {       353}, { 33} }, // declarator_id   
    { {        40}, { 34} }, // '('             
    { {        42}, { 35} }, // '*'             
    { {        38}, { 36} }, // '&'             
    { {       376}, { 40} }, // identifier      
    { {       257}, { 37} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -95} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 62} }, // ';'
    { {        44}, { 42} }, // ','
    { {         0}, {  0} },       
};

SR__ s_39[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 12} },                    
    { {       340}, { 63} }, // init_declarator 
    { {       342}, { 21} }, // declarator      
    { {       343}, { 24} }, // ptr_declarator  
    { {       345}, { 27} }, // noptr_declarator
    { {       344}, { 28} }, // ptr_operator    
    { {       353}, { 33} }, // declarator_id   
    { {        40}, { 34} }, // '('             
    { {        42}, { 35} }, // '*'             
    { {        38}, { 36} }, // '&'             
    { {       376}, { 40} }, // identifier      
    { {       257}, { 37} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 64} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_44[] =
{
    { { DEF_RED}, {  2} },                   
    { {     333}, { 65} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       376}, { 66} }, // identifier
    { {       123}, { 67} }, // '{'       
    { {       257}, { 37} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 23} },                       
    { {       355}, { 68} }, // initializer_clause 
    { {       346}, { 69} }, // expression         
    { {       373}, { 70} }, // term               
    { {       374}, { 71} }, // literal            
    { {       376}, { 72} }, // identifier         
    { {       375}, { 73} }, // operand            
    { {        40}, { 74} }, // '('                
    { {       294}, { 75} }, // STRING_LITERAL     
    { {       295}, { 76} }, // CHARACTER_LITERAL  
    { {       296}, { 77} }, // INTEGER_LITERAL    
    { {       297}, { 78} }, // HEXADECIMAL_LITERAL
    { {       298}, { 79} }, // OCTAL_LITERAL      
    { {       299}, { 80} }, // FLOAT_LITERAL      
    { {       257}, { 37} }, // IDENTIFIER         
    { {        43}, { 81} }, // '+'                
    { {        45}, { 82} }, // '-'                
    { {        42}, { 83} }, // '*'                
    { {        47}, { 84} }, // '/'                
    { {        37}, { 85} }, // '%'                
    { {        94}, { 86} }, // '^'                
    { {        63}, { 87} }, // '?'                
    { {        58}, { 88} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 89} }, // '}'
    { {         0}, {  0} },       
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   3} },               
    { {     367}, {  90} }, // base_clause
    { {      58}, {  54} }, // ':'        
    { {       0}, { -56} },               
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 12} },                       
    { {       368}, { 91} }, // base_specifier_list
    { {       369}, { 92} }, // base_specifier     
    { {       370}, { 93} }, // base_type_specifier
    { {       291}, { 94} }, // VIRTUAL            
    { {       371}, { 95} }, // access_specifier   
    { {       372}, { 96} }, // class_name         
    { {       272}, { 97} }, // PRIVATE            
    { {       273}, { 98} }, // PROTECTED          
    { {       274}, { 99} }, // PUBLIC             
    { {       376}, { 56} }, // identifier         
    { {       257}, { 37} }, // IDENTIFIER         
    { {         0}, {  0} },                       
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  23} },                       
    { {       346}, { 100} }, // expression         
    { {        93}, { 101} }, // ']'                
    { {       373}, {  70} }, // term               
    { {       374}, {  71} }, // literal            
    { {       376}, {  72} }, // identifier         
    { {       375}, {  73} }, // operand            
    { {        40}, {  74} }, // '('                
    { {       294}, {  75} }, // STRING_LITERAL     
    { {       295}, {  76} }, // CHARACTER_LITERAL  
    { {       296}, {  77} }, // INTEGER_LITERAL    
    { {       297}, {  78} }, // HEXADECIMAL_LITERAL
    { {       298}, {  79} }, // OCTAL_LITERAL      
    { {       299}, {  80} }, // FLOAT_LITERAL      
    { {       257}, {  37} }, // IDENTIFIER         
    { {        43}, {  81} }, // '+'                
    { {        45}, {  82} }, // '-'                
    { {        42}, {  83} }, // '*'                
    { {        47}, {  84} }, // '/'                
    { {        37}, {  85} }, // '%'                
    { {        94}, {  86} }, // '^'                
    { {        63}, {  87} }, // '?'                
    { {        58}, {  88} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_59[] =
{
    { { REQ_DEF}, {  20} },                                
    { {     348}, { 102} }, // parameter_declaration_clause
    { {     349}, { 103} }, // parameter_declaration_list  
    { {     350}, { 104} }, // parameter_declaration       
    { {     337}, { 105} }, // decl_specifier_seq          
    { {     359}, {  14} }, // type_specifier              
    { {     338}, {  15} }, // decl_specifier              
    { {     360}, {  17} }, // trailing_type_specifier     
    { {     363}, {  18} }, // class_specifier             
    { {     267}, {  19} }, // FRIEND                      
    { {     285}, {  20} }, // TYPEDEF                     
    { {     361}, {  22} }, // simple_type_specifier       
    { {     364}, {  23} }, // class_head                  
    { {     362}, {  25} }, // type_name                   
    { {     365}, {  26} }, // class_key                   
    { {     376}, {  47} }, // identifier                  
    { {     260}, {  30} }, // CLASS                       
    { {     288}, {  31} }, // UNION                       
    { {     280}, {  32} }, // STRUCT                      
    { {     257}, {  37} }, // IDENTIFIER                  
    { {       0}, { -28} },                                
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 106} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_62[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   2} },                   
    { {     333}, { 107} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  37} },                                
    { {       125}, { 108} }, // '}'                         
    { {       334}, {   3} }, // declaration                 
    { {       335}, {   4} }, // block_declaration           
    { {       356}, {   5} }, // namespace_definition        
    { {       336}, {   6} }, // simple_declaration          
    { {       357}, {   7} }, // named_namespace_definition  
    { {       358}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       337}, {  10} }, // decl_specifier_seq          
    { {       339}, {  11} }, // init_declarator_list        
    { {       270}, {  12} }, // NAMESPACE                   
    { {       268}, {  13} }, // INLINE                      
    { {       359}, {  14} }, // type_specifier              
    { {       338}, {  15} }, // decl_specifier              
    { {       340}, {  16} }, // init_declarator             
    { {       360}, {  17} }, // trailing_type_specifier     
    { {       363}, {  18} }, // class_specifier             
    { {       267}, {  19} }, // FRIEND                      
    { {       285}, {  20} }, // TYPEDEF                     
    { {       342}, {  21} }, // declarator                  
    { {       361}, {  22} }, // simple_type_specifier       
    { {       364}, {  23} }, // class_head                  
    { {       343}, {  24} }, // ptr_declarator              
    { {       362}, {  25} }, // type_name                   
    { {       365}, {  26} }, // class_key                   
    { {       345}, {  27} }, // noptr_declarator            
    { {       344}, {  28} }, // ptr_operator                
    { {       376}, {  29} }, // identifier                  
    { {       260}, {  30} }, // CLASS                       
    { {       288}, {  31} }, // UNION                       
    { {       280}, {  32} }, // STRUCT                      
    { {       353}, {  33} }, // declarator_id               
    { {        40}, {  34} }, // '('                         
    { {        42}, {  35} }, // '*'                         
    { {        38}, {  36} }, // '&'                         
    { {       257}, {  37} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       123}, { 109} }, // '{'
    { {         0}, {   0} },       
};

SR__ s_67[] =
{
    { { DEF_RED}, {   2} },                   
    { {     333}, { 110} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     373}, { 111} }, // term               
    { {     374}, {  71} }, // literal            
    { {     376}, {  72} }, // identifier         
    { {     375}, {  73} }, // operand            
    { {      40}, {  74} }, // '('                
    { {     294}, {  75} }, // STRING_LITERAL     
    { {     295}, {  76} }, // CHARACTER_LITERAL  
    { {     296}, {  77} }, // INTEGER_LITERAL    
    { {     297}, {  78} }, // HEXADECIMAL_LITERAL
    { {     298}, {  79} }, // OCTAL_LITERAL      
    { {     299}, {  80} }, // FLOAT_LITERAL      
    { {     257}, {  37} }, // IDENTIFIER         
    { {      43}, {  81} }, // '+'                
    { {      45}, {  82} }, // '-'                
    { {      42}, {  83} }, // '*'                
    { {      47}, {  84} }, // '/'                
    { {      37}, {  85} }, // '%'                
    { {      94}, {  86} }, // '^'                
    { {      63}, {  87} }, // '?'                
    { {      58}, {  88} }, // ':'                
    { {       0}, { -41} },                       
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {       346}, { 112} }, // expression         
    { {       373}, {  70} }, // term               
    { {       374}, {  71} }, // literal            
    { {       376}, {  72} }, // identifier         
    { {       375}, {  73} }, // operand            
    { {        40}, {  74} }, // '('                
    { {       294}, {  75} }, // STRING_LITERAL     
    { {       295}, {  76} }, // CHARACTER_LITERAL  
    { {       296}, {  77} }, // INTEGER_LITERAL    
    { {       297}, {  78} }, // HEXADECIMAL_LITERAL
    { {       298}, {  79} }, // OCTAL_LITERAL      
    { {       299}, {  80} }, // FLOAT_LITERAL      
    { {       257}, {  37} }, // IDENTIFIER         
    { {        43}, {  81} }, // '+'                
    { {        45}, {  82} }, // '-'                
    { {        42}, {  83} }, // '*'                
    { {        47}, {  84} }, // '/'                
    { {        37}, {  85} }, // '%'                
    { {        94}, {  86} }, // '^'                
    { {        63}, {  87} }, // '?'                
    { {        58}, {  88} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -88} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -89} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -90} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -91} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -92} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -93} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -94} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 113} }, // ','
    { {       0}, { -59} },       
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   9} },                       
    { {       370}, { 114} }, // base_type_specifier
    { {       371}, { 115} }, // access_specifier   
    { {       372}, {  96} }, // class_name         
    { {       272}, {  97} }, // PRIVATE            
    { {       273}, {  98} }, // PROTECTED          
    { {       274}, {  99} }, // PUBLIC             
    { {       376}, {  56} }, // identifier         
    { {       257}, {  37} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   6} },                       
    { {       370}, { 116} }, // base_type_specifier
    { {       291}, { 117} }, // VIRTUAL            
    { {       372}, {  96} }, // class_name         
    { {       376}, {  56} }, // identifier         
    { {       257}, {  37} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {        93}, { 118} }, // ']'                
    { {       373}, { 111} }, // term               
    { {       374}, {  71} }, // literal            
    { {       376}, {  72} }, // identifier         
    { {       375}, {  73} }, // operand            
    { {        40}, {  74} }, // '('                
    { {       294}, {  75} }, // STRING_LITERAL     
    { {       295}, {  76} }, // CHARACTER_LITERAL  
    { {       296}, {  77} }, // INTEGER_LITERAL    
    { {       297}, {  78} }, // HEXADECIMAL_LITERAL
    { {       298}, {  79} }, // OCTAL_LITERAL      
    { {       299}, {  80} }, // FLOAT_LITERAL      
    { {       257}, {  37} }, // IDENTIFIER         
    { {        43}, {  81} }, // '+'                
    { {        45}, {  82} }, // '-'                
    { {        42}, {  83} }, // '*'                
    { {        47}, {  84} }, // '/'                
    { {        37}, {  85} }, // '%'                
    { {        94}, {  86} }, // '^'                
    { {        63}, {  87} }, // '?'                
    { {        58}, {  88} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 119} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 120} }, // ','
    { {       0}, { -29} },       
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_105[] =
{
    { { REQ_DEF}, {  11} },                    
    { {     342}, { 121} }, // declarator      
    { {     343}, {  24} }, // ptr_declarator  
    { {     345}, {  27} }, // noptr_declarator
    { {     344}, {  28} }, // ptr_operator    
    { {     353}, {  33} }, // declarator_id   
    { {      40}, {  34} }, // '('             
    { {      42}, {  35} }, // '*'             
    { {      38}, {  36} }, // '&'             
    { {     376}, {  40} }, // identifier      
    { {     257}, {  37} }, // IDENTIFIER      
    { {       0}, { -32} },                    
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {  37} },                                
    { {       125}, { 122} }, // '}'                         
    { {       334}, {   3} }, // declaration                 
    { {       335}, {   4} }, // block_declaration           
    { {       356}, {   5} }, // namespace_definition        
    { {       336}, {   6} }, // simple_declaration          
    { {       357}, {   7} }, // named_namespace_definition  
    { {       358}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       337}, {  10} }, // decl_specifier_seq          
    { {       339}, {  11} }, // init_declarator_list        
    { {       270}, {  12} }, // NAMESPACE                   
    { {       268}, {  13} }, // INLINE                      
    { {       359}, {  14} }, // type_specifier              
    { {       338}, {  15} }, // decl_specifier              
    { {       340}, {  16} }, // init_declarator             
    { {       360}, {  17} }, // trailing_type_specifier     
    { {       363}, {  18} }, // class_specifier             
    { {       267}, {  19} }, // FRIEND                      
    { {       285}, {  20} }, // TYPEDEF                     
    { {       342}, {  21} }, // declarator                  
    { {       361}, {  22} }, // simple_type_specifier       
    { {       364}, {  23} }, // class_head                  
    { {       343}, {  24} }, // ptr_declarator              
    { {       362}, {  25} }, // type_name                   
    { {       365}, {  26} }, // class_key                   
    { {       345}, {  27} }, // noptr_declarator            
    { {       344}, {  28} }, // ptr_operator                
    { {       376}, {  29} }, // identifier                  
    { {       260}, {  30} }, // CLASS                       
    { {       288}, {  31} }, // UNION                       
    { {       280}, {  32} }, // STRUCT                      
    { {       353}, {  33} }, // declarator_id               
    { {        40}, {  34} }, // '('                         
    { {        42}, {  35} }, // '*'                         
    { {        38}, {  36} }, // '&'                         
    { {       257}, {  37} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   2} },                   
    { {     333}, { 123} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {  37} },                                
    { {       125}, { 124} }, // '}'                         
    { {       334}, {   3} }, // declaration                 
    { {       335}, {   4} }, // block_declaration           
    { {       356}, {   5} }, // namespace_definition        
    { {       336}, {   6} }, // simple_declaration          
    { {       357}, {   7} }, // named_namespace_definition  
    { {       358}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       337}, {  10} }, // decl_specifier_seq          
    { {       339}, {  11} }, // init_declarator_list        
    { {       270}, {  12} }, // NAMESPACE                   
    { {       268}, {  13} }, // INLINE                      
    { {       359}, {  14} }, // type_specifier              
    { {       338}, {  15} }, // decl_specifier              
    { {       340}, {  16} }, // init_declarator             
    { {       360}, {  17} }, // trailing_type_specifier     
    { {       363}, {  18} }, // class_specifier             
    { {       267}, {  19} }, // FRIEND                      
    { {       285}, {  20} }, // TYPEDEF                     
    { {       342}, {  21} }, // declarator                  
    { {       361}, {  22} }, // simple_type_specifier       
    { {       364}, {  23} }, // class_head                  
    { {       343}, {  24} }, // ptr_declarator              
    { {       362}, {  25} }, // type_name                   
    { {       365}, {  26} }, // class_key                   
    { {       345}, {  27} }, // noptr_declarator            
    { {       344}, {  28} }, // ptr_operator                
    { {       376}, {  29} }, // identifier                  
    { {       260}, {  30} }, // CLASS                       
    { {       288}, {  31} }, // UNION                       
    { {       280}, {  32} }, // STRUCT                      
    { {       353}, {  33} }, // declarator_id               
    { {        40}, {  34} }, // '('                         
    { {        42}, {  35} }, // '*'                         
    { {        38}, {  36} }, // '&'                         
    { {       257}, {  37} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {        41}, { 125} }, // ')'                
    { {       373}, { 111} }, // term               
    { {       374}, {  71} }, // literal            
    { {       376}, {  72} }, // identifier         
    { {       375}, {  73} }, // operand            
    { {        40}, {  74} }, // '('                
    { {       294}, {  75} }, // STRING_LITERAL     
    { {       295}, {  76} }, // CHARACTER_LITERAL  
    { {       296}, {  77} }, // INTEGER_LITERAL    
    { {       297}, {  78} }, // HEXADECIMAL_LITERAL
    { {       298}, {  79} }, // OCTAL_LITERAL      
    { {       299}, {  80} }, // FLOAT_LITERAL      
    { {       257}, {  37} }, // IDENTIFIER         
    { {        43}, {  81} }, // '+'                
    { {        45}, {  82} }, // '-'                
    { {        42}, {  83} }, // '*'                
    { {        47}, {  84} }, // '/'                
    { {        37}, {  85} }, // '%'                
    { {        94}, {  86} }, // '^'                
    { {        63}, {  87} }, // '?'                
    { {        58}, {  88} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {  11} },                       
    { {       369}, { 126} }, // base_specifier     
    { {       370}, {  93} }, // base_type_specifier
    { {       291}, {  94} }, // VIRTUAL            
    { {       371}, {  95} }, // access_specifier   
    { {       372}, {  96} }, // class_name         
    { {       272}, {  97} }, // PRIVATE            
    { {       273}, {  98} }, // PROTECTED          
    { {       274}, {  99} }, // PUBLIC             
    { {       376}, {  56} }, // identifier         
    { {       257}, {  37} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   5} },                       
    { {       370}, { 127} }, // base_type_specifier
    { {       372}, {  96} }, // class_name         
    { {       376}, {  56} }, // identifier         
    { {       257}, {  37} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {   5} },                       
    { {       370}, { 128} }, // base_type_specifier
    { {       372}, {  96} }, // class_name         
    { {       376}, {  56} }, // identifier         
    { {       257}, {  37} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  18} },                           
    { {       350}, { 129} }, // parameter_declaration  
    { {       337}, { 105} }, // decl_specifier_seq     
    { {       359}, {  14} }, // type_specifier         
    { {       338}, {  15} }, // decl_specifier         
    { {       360}, {  17} }, // trailing_type_specifier
    { {       363}, {  18} }, // class_specifier        
    { {       267}, {  19} }, // FRIEND                 
    { {       285}, {  20} }, // TYPEDEF                
    { {       361}, {  22} }, // simple_type_specifier  
    { {       364}, {  23} }, // class_head             
    { {       362}, {  25} }, // type_name              
    { {       365}, {  26} }, // class_key              
    { {       376}, {  47} }, // identifier             
    { {       260}, {  30} }, // CLASS                  
    { {       288}, {  31} }, // UNION                  
    { {       280}, {  32} }, // STRUCT                 
    { {       257}, {  37} }, // IDENTIFIER             
    { {         0}, {   0} },                           
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {  37} },                                
    { {       125}, { 130} }, // '}'                         
    { {       334}, {   3} }, // declaration                 
    { {       335}, {   4} }, // block_declaration           
    { {       356}, {   5} }, // namespace_definition        
    { {       336}, {   6} }, // simple_declaration          
    { {       357}, {   7} }, // named_namespace_definition  
    { {       358}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       337}, {  10} }, // decl_specifier_seq          
    { {       339}, {  11} }, // init_declarator_list        
    { {       270}, {  12} }, // NAMESPACE                   
    { {       268}, {  13} }, // INLINE                      
    { {       359}, {  14} }, // type_specifier              
    { {       338}, {  15} }, // decl_specifier              
    { {       340}, {  16} }, // init_declarator             
    { {       360}, {  17} }, // trailing_type_specifier     
    { {       363}, {  18} }, // class_specifier             
    { {       267}, {  19} }, // FRIEND                      
    { {       285}, {  20} }, // TYPEDEF                     
    { {       342}, {  21} }, // declarator                  
    { {       361}, {  22} }, // simple_type_specifier       
    { {       364}, {  23} }, // class_head                  
    { {       343}, {  24} }, // ptr_declarator              
    { {       362}, {  25} }, // type_name                   
    { {       365}, {  26} }, // class_key                   
    { {       345}, {  27} }, // noptr_declarator            
    { {       344}, {  28} }, // ptr_operator                
    { {       376}, {  29} }, // identifier                  
    { {       260}, {  30} }, // CLASS                       
    { {       288}, {  31} }, // UNION                       
    { {       280}, {  32} }, // STRUCT                      
    { {       353}, {  33} }, // declarator_id               
    { {        40}, {  34} }, // '('                         
    { {        42}, {  35} }, // '*'                         
    { {        38}, {  36} }, // '&'                         
    { {       257}, {  37} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_129[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,
};

} // anonymous namespace ends


// $insert namespace-open
namespace opwig
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

MDParserBase::MDParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void MDParser::print__()
{
// $insert print
}

void MDParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void MDParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void MDParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void MDParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void MDParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t MDParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void MDParser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 114 "mdparser.gr"
        {
         for (auto it: *d_vsp__[0].data<Tag__::DeclarationSeq>())
         if (!(it) (global_namespace_))
         std::cout << "Namespace action failed (global)";
         }
        break;

        case 2:
#line 122 "mdparser.gr"
        {
         d_val__.get<Tag__::DeclarationSeq>() = std::shared_ptr<ScopeActionList>(new ScopeActionList);
         }
        break;

        case 3:
#line 126 "mdparser.gr"
        {
         (d_vsp__[-1].data<Tag__::DeclarationSeq>())->push_back(d_vsp__[0].data<Tag__::Declaration>());
         d_val__.get<Tag__::DeclarationSeq>() = d_vsp__[-1].data<Tag__::DeclarationSeq>();
         }
        break;

        case 4:
#line 133 "mdparser.gr"
        {
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 5:
#line 137 "mdparser.gr"
        { 
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 6:
#line 147 "mdparser.gr"
        { d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>(); }
        break;

        case 8:
#line 153 "mdparser.gr"
        {
         TypeAction type_action = d_vsp__[-2].data<Tag__::Type>();
         std::shared_ptr<parser::DeclaratorList> init_list = d_vsp__[-1].data<Tag__::DeclaratorSeq>();
         d_val__.get<Tag__::Declaration>() = [type_action, init_list] (md::Ptr<md::Scope> current_namespace) -> bool {
         for (auto declarator: *init_list) {
         std::string type = type_action(current_namespace);
         if (declarator.has_parameters()) {
         md::Ptr<md::Function> func =
         md::Function::Create(declarator.name(), type, declarator.parameters());
         if (!current_namespace->AddNestedFunction(func));
         } else {
         md::Ptr<md::Variable> var = md::Variable::Create(declarator.name(), type);
         if (!current_namespace->AddGlobalVariable(var)) {
         
         }
         }
         }
         return true;
         };
         }
        break;

        case 9:
#line 174 "mdparser.gr"
        {
         TypeAction type_action = d_vsp__[-1].data<Tag__::Type>();
         d_val__.get<Tag__::Declaration>() = [type_action] (md::Ptr<md::Scope> current_namespace) -> bool {
         type_action(current_namespace);
         return true;
         };
         }
        break;

        case 11:
#line 186 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 12:
#line 188 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 15:
#line 200 "mdparser.gr"
        {
         d_val__.get<Tag__::DeclaratorSeq>() = std::shared_ptr<parser::DeclaratorList>(new parser::DeclaratorList);
         (d_val__.get<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         }
        break;

        case 16:
#line 205 "mdparser.gr"
        {
         (d_vsp__[-2].data<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         d_val__.get<Tag__::DeclaratorSeq>() = d_vsp__[-2].data<Tag__::DeclaratorSeq>();
         }
        break;

        case 17:
#line 212 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 18:
#line 214 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 19:
#line 218 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 20:
#line 222 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 21:
#line 224 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 22:
#line 228 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = parser::Declarator(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 23:
#line 230 "mdparser.gr"
        {
         d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>();
         (d_val__.get<Tag__::Declarator>()).set_parameters(d_vsp__[0].data<Tag__::ParameterSeq>());
         }
        break;

        case 24:
#line 235 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-3].data<Tag__::Declarator>(); }
        break;

        case 25:
#line 237 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-2].data<Tag__::Declarator>(); }
        break;

        case 26:
#line 239 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 27:
#line 243 "mdparser.gr"
        { d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-1].data<Tag__::ParameterSeq>(); }
        break;

        case 28:
#line 253 "mdparser.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = std::shared_ptr<md::ParameterList>(new md::ParameterList);
         }
        break;

        case 29:
#line 257 "mdparser.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = d_vsp__[0].data<Tag__::ParameterSeq>();
         }
        break;

        case 30:
#line 263 "mdparser.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = std::shared_ptr<md::ParameterList>(new md::ParameterList);
         (d_val__.get<Tag__::ParameterSeq>())->push_back(d_vsp__[0].data<Tag__::Parameter>());
         }
        break;

        case 31:
#line 268 "mdparser.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-2].data<Tag__::ParameterSeq>();
         (d_val__.get<Tag__::ParameterSeq>())->push_back(d_vsp__[0].data<Tag__::Parameter>());
         }
        break;

        case 32:
#line 275 "mdparser.gr"
        { d_val__.get<Tag__::Parameter>() = md::Parameter((d_vsp__[0].data<Tag__::Type>())(md::Ptr<md::Scope>()), ""); }
        break;

        case 33:
#line 277 "mdparser.gr"
        { d_val__.get<Tag__::Parameter>() = md::Parameter((d_vsp__[-1].data<Tag__::Type>())(md::Ptr<md::Scope>()), (d_vsp__[0].data<Tag__::Declarator>()).name()); }
        break;

        case 34:
#line 281 "mdparser.gr"
        {}
        break;

        case 35:
#line 285 "mdparser.gr"
        {}
        break;

        case 38:
#line 295 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 42:
#line 336 "mdparser.gr"
        {
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 43:
#line 340 "mdparser.gr"
        {
         d_val__.get<Tag__::Declaration>() = [] (md::Ptr<md::Scope> current_namespace) -> bool { return true; };
         }
        break;

        case 44:
#line 346 "mdparser.gr"
        {
         using md::Namespace;
         using md::Ptr;
         Ptr<Namespace> new_namespace = Namespace::Create();
         std::string name = d_vsp__[-3].data<Tag__::String>();
         for (auto it: *d_vsp__[-1].data<Tag__::DeclarationSeq>())
         if (!(it) (new_namespace))
         std::cout << "Namespace action failed (new)";
         d_val__.get<Tag__::Declaration>() = [name,new_namespace] (Ptr<md::Scope> current_namespace) -> bool {
         return current_namespace->AddNestedNamespace(name, new_namespace);
         };
         }
        break;

        case 48:
#line 371 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 49:
#line 373 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 50:
#line 377 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 51:
#line 381 "mdparser.gr"
        { 
         std::string name = d_vsp__[0].data<Tag__::String>();
         d_val__.get<Tag__::Type>() = [name] (md::Ptr<md::Scope> current_namespace) -> std::string {
         return name;
         }; 
         }
        break;

        case 52:
#line 390 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 53:
#line 396 "mdparser.gr"
        {
         md::Ptr<md::Class> classObj = d_vsp__[-2].data<Tag__::Class>();
         d_val__.get<Tag__::Type>() = [classObj] (md::Ptr<md::Scope> current_namespace) -> std::string {
         if (current_namespace->AddNestedClass(classObj->name(), classObj))
         return classObj->name();
         throw md::SemanticError("Non-anonymous class cannot have empty name!");
         };
         }
        break;

        case 54:
#line 407 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create("", BaseSpecifierList()); }
        break;

        case 55:
#line 409 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create("", *d_vsp__[0].data<Tag__::BaseSpecifierSeq>()); }
        break;

        case 56:
#line 411 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create(d_vsp__[0].data<Tag__::String>(), BaseSpecifierList()); }
        break;

        case 57:
#line 413 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create(d_vsp__[-1].data<Tag__::String>(), *d_vsp__[0].data<Tag__::BaseSpecifierSeq>()); }
        break;

        case 58:
#line 417 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 59:
#line 421 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifierSeq>() = d_vsp__[0].data<Tag__::BaseSpecifierSeq>(); }
        break;

        case 60:
#line 425 "mdparser.gr"
        {
         d_val__.get<Tag__::BaseSpecifierSeq>() = std::shared_ptr<BaseSpecifierList>(new BaseSpecifierList);
         (d_val__.get<Tag__::BaseSpecifierSeq>())->push_back(d_vsp__[0].data<Tag__::BaseSpecifier>());
         }
        break;

        case 61:
#line 430 "mdparser.gr"
        {
         (d_vsp__[-2].data<Tag__::BaseSpecifierSeq>())->push_back(d_vsp__[0].data<Tag__::BaseSpecifier>());
         d_val__.get<Tag__::BaseSpecifierSeq>() = d_vsp__[-2].data<Tag__::BaseSpecifierSeq>();
         }
        break;

        case 62:
#line 437 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 63:
#line 439 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true); }
        break;

        case 64:
#line 441 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), d_vsp__[-1].data<Tag__::AccessSpecifier>()); }
        break;

        case 65:
#line 443 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true, d_vsp__[-1].data<Tag__::AccessSpecifier>()); }
        break;

        case 66:
#line 445 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true, d_vsp__[-2].data<Tag__::AccessSpecifier>()); }
        break;

        case 67:
#line 449 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 68:
#line 453 "mdparser.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = parser::AccessSpecifier::PRIVATE; }
        break;

        case 69:
#line 455 "mdparser.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = parser::AccessSpecifier::PROTECTED; }
        break;

        case 70:
#line 457 "mdparser.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = parser::AccessSpecifier::PUBLIC; }
        break;

        case 71:
#line 461 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 95:
#line 506 "mdparser.gr"
        {
         d_val__.get<Tag__::String>() = d_scanner.matched();
         }
        break;

    }
}

inline void MDParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void MDParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int MDParser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void MDParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int MDParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}


// $insert namespace-close
}


