// Generated by Bisonc++ V4.01.00 on Mon, 08 Apr 2013 20:21:54 -0300

// $insert class.ih
#include "mdparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {330, 1}, // 1: input ->  declaration_seq
     {331, 0}, // 2: declaration_seq ->  <empty>
     {331, 2}, // 3: declaration_seq ->  declaration_seq declaration
     {332, 1}, // 4: declaration ->  block_declaration
     {332, 1}, // 5: declaration ->  namespace_definition
     {333, 1}, // 6: block_declaration ->  simple_declaration
     {334, 1}, // 7: simple_declaration (';') ->  ';'
     {334, 3}, // 8: simple_declaration (';') ->  decl_specifier_seq init_declarator_list ';'
     {334, 2}, // 9: simple_declaration (';') ->  decl_specifier_seq ';'
     {335, 1}, // 10: decl_specifier_seq ->  type_specifier
     {335, 2}, // 11: decl_specifier_seq ->  decl_specifier decl_specifier_seq
     {336, 1}, // 12: decl_specifier (FRIEND) ->  FRIEND
     {336, 1}, // 13: decl_specifier (TYPEDEF) ->  TYPEDEF
     {337, 1}, // 14: init_declarator_list ->  init_declarator
     {337, 3}, // 15: init_declarator_list (',') ->  init_declarator_list ',' init_declarator
     {338, 1}, // 16: init_declarator ->  declarator
     {338, 2}, // 17: init_declarator ->  declarator initializer
     {340, 1}, // 18: declarator ->  ptr_declarator
     {341, 1}, // 19: ptr_declarator ->  noptr_declarator
     {341, 2}, // 20: ptr_declarator ->  ptr_operator ptr_declarator
     {343, 1}, // 21: noptr_declarator ->  declarator_id
     {343, 2}, // 22: noptr_declarator ->  noptr_declarator parameters_and_qualifiers
     {343, 4}, // 23: noptr_declarator ('[') ->  noptr_declarator '[' expression ']'
     {343, 3}, // 24: noptr_declarator ('(') ->  '(' ptr_declarator ')'
     {345, 3}, // 25: parameters_and_qualifiers ('(') ->  '(' parameter_declaration_clause ')'
     {345, 4}, // 26: parameters_and_qualifiers ('(') ->  '(' parameter_declaration_clause ')' cv_qualifier_seq
     {345, 4}, // 27: parameters_and_qualifiers ('(') ->  '(' parameter_declaration_clause ')' exception_especification
     {345, 5}, // 28: parameters_and_qualifiers ('(') ->  '(' parameter_declaration_clause ')' cv_qualifier_seq exception_especification
     {348, 0}, // 29: parameter_declaration_clause ->  <empty>
     {346, 0}, // 30: cv_qualifier_seq ->  <empty>
     {347, 0}, // 31: exception_especification ->  <empty>
     {342, 1}, // 32: ptr_operator ('*') ->  '*'
     {342, 1}, // 33: ptr_operator ('&') ->  '&'
     {349, 1}, // 34: declarator_id ->  identifier
     {339, 1}, // 35: initializer ->  brace_or_equal_initializer
     {350, 2}, // 36: brace_or_equal_initializer ('=') ->  '=' initializer_clause
     {351, 1}, // 37: initializer_clause ->  expression
     {352, 1}, // 38: namespace_definition ->  named_namespace_definition
     {352, 1}, // 39: namespace_definition ->  unnamed_namespace_definition
     {353, 5}, // 40: named_namespace_definition (NAMESPACE) ->  NAMESPACE identifier '{' declaration_seq '}'
     {353, 6}, // 41: named_namespace_definition (INLINE) ->  INLINE NAMESPACE identifier '{' declaration_seq '}'
     {354, 4}, // 42: unnamed_namespace_definition (NAMESPACE) ->  NAMESPACE '{' declaration_seq '}'
     {354, 5}, // 43: unnamed_namespace_definition (INLINE) ->  INLINE NAMESPACE '{' declaration_seq '}'
     {355, 1}, // 44: type_specifier ->  trailing_type_specifier
     {355, 1}, // 45: type_specifier ->  class_specifier
     {356, 1}, // 46: trailing_type_specifier ->  simple_type_specifier
     {357, 1}, // 47: simple_type_specifier ->  type_name
     {358, 1}, // 48: type_name ->  identifier
     {359, 3}, // 49: class_specifier ('{') ->  class_head '{' '}'
     {360, 1}, // 50: class_head ->  class_key
     {360, 2}, // 51: class_head ->  class_key base_clause
     {360, 2}, // 52: class_head ->  class_key class_head_name
     {360, 3}, // 53: class_head ->  class_key class_head_name base_clause
     {362, 1}, // 54: class_head_name ->  class_name
     {363, 2}, // 55: base_clause (':') ->  ':' base_specifier_list
     {364, 1}, // 56: base_specifier_list ->  base_specifier
     {364, 3}, // 57: base_specifier_list (',') ->  base_specifier_list ',' base_specifier
     {365, 1}, // 58: base_specifier ->  base_type_specifier
     {365, 2}, // 59: base_specifier (VIRTUAL) ->  VIRTUAL base_type_specifier
     {365, 2}, // 60: base_specifier ->  access_specifier base_type_specifier
     {365, 3}, // 61: base_specifier (VIRTUAL) ->  VIRTUAL access_specifier base_type_specifier
     {365, 3}, // 62: base_specifier (VIRTUAL) ->  access_specifier VIRTUAL base_type_specifier
     {366, 1}, // 63: base_type_specifier ->  class_name
     {367, 1}, // 64: access_specifier (PRIVATE) ->  PRIVATE
     {367, 1}, // 65: access_specifier (PROTECTED) ->  PROTECTED
     {367, 1}, // 66: access_specifier (PUBLIC) ->  PUBLIC
     {368, 1}, // 67: class_name ->  identifier
     {361, 1}, // 68: class_key (CLASS) ->  CLASS
     {361, 1}, // 69: class_key (UNION) ->  UNION
     {361, 1}, // 70: class_key (STRUCT) ->  STRUCT
     {344, 1}, // 71: expression ->  term
     {344, 2}, // 72: expression ->  expression term
     {369, 1}, // 73: term ->  literal
     {369, 1}, // 74: term ->  identifier
     {369, 1}, // 75: term ->  operand
     {369, 3}, // 76: term ('(') ->  '(' expression ')'
     {370, 1}, // 77: literal (STRING_LITERAL) ->  STRING_LITERAL
     {370, 1}, // 78: literal (CHARACTER_LITERAL) ->  CHARACTER_LITERAL
     {370, 1}, // 79: literal (INTEGER_LITERAL) ->  INTEGER_LITERAL
     {370, 1}, // 80: literal (HEXADECIMAL_LITERAL) ->  HEXADECIMAL_LITERAL
     {370, 1}, // 81: literal (OCTAL_LITERAL) ->  OCTAL_LITERAL
     {370, 1}, // 82: literal (FLOAT_LITERAL) ->  FLOAT_LITERAL
     {371, 1}, // 83: operand ('+') ->  '+'
     {371, 1}, // 84: operand ('-') ->  '-'
     {371, 1}, // 85: operand ('*') ->  '*'
     {371, 1}, // 86: operand ('/') ->  '/'
     {371, 1}, // 87: operand ('%') ->  '%'
     {371, 1}, // 88: operand ('^') ->  '^'
     {371, 1}, // 89: operand ('?') ->  '?'
     {371, 1}, // 90: operand (':') ->  ':'
     {372, 1}, // 91: identifier (IDENTIFIER) ->  IDENTIFIER
     {373, 1}, // 92: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  3} },                   
    { {     330}, {  1} }, // input          
    { {     331}, {  2} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 26} },                                
    { {     332}, {  3} }, // declaration                 
    { {     333}, {  4} }, // block_declaration           
    { {     352}, {  5} }, // namespace_definition        
    { {     334}, {  6} }, // simple_declaration          
    { {     353}, {  7} }, // named_namespace_definition  
    { {     354}, {  8} }, // unnamed_namespace_definition
    { {      59}, {  9} }, // ';'                         
    { {     335}, { 10} }, // decl_specifier_seq          
    { {     270}, { 11} }, // NAMESPACE                   
    { {     268}, { 12} }, // INLINE                      
    { {     355}, { 13} }, // type_specifier              
    { {     336}, { 14} }, // decl_specifier              
    { {     356}, { 15} }, // trailing_type_specifier     
    { {     359}, { 16} }, // class_specifier             
    { {     267}, { 17} }, // FRIEND                      
    { {     285}, { 18} }, // TYPEDEF                     
    { {     357}, { 19} }, // simple_type_specifier       
    { {     360}, { 20} }, // class_head                  
    { {     358}, { 21} }, // type_name                   
    { {     361}, { 22} }, // class_key                   
    { {     372}, { 23} }, // identifier                  
    { {     260}, { 24} }, // CLASS                       
    { {     288}, { 25} }, // UNION                       
    { {     280}, { 26} }, // STRUCT                      
    { {     257}, { 27} }, // IDENTIFIER                  
    { {       0}, { -1} },                                
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       337}, { 28} }, // init_declarator_list
    { {        59}, { 29} }, // ';'                 
    { {       338}, { 30} }, // init_declarator     
    { {       340}, { 31} }, // declarator          
    { {       341}, { 32} }, // ptr_declarator      
    { {       343}, { 33} }, // noptr_declarator    
    { {       342}, { 34} }, // ptr_operator        
    { {       349}, { 35} }, // declarator_id       
    { {        40}, { 36} }, // '('                 
    { {        42}, { 37} }, // '*'                 
    { {        38}, { 38} }, // '&'                 
    { {       372}, { 39} }, // identifier          
    { {       257}, { 27} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       372}, { 40} }, // identifier
    { {       123}, { 41} }, // '{'       
    { {       257}, { 27} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       270}, { 42} }, // NAMESPACE
    { {         0}, {  0} },             
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 17} },                           
    { {       335}, { 43} }, // decl_specifier_seq     
    { {       355}, { 13} }, // type_specifier         
    { {       336}, { 14} }, // decl_specifier         
    { {       356}, { 15} }, // trailing_type_specifier
    { {       359}, { 16} }, // class_specifier        
    { {       267}, { 17} }, // FRIEND                 
    { {       285}, { 18} }, // TYPEDEF                
    { {       357}, { 19} }, // simple_type_specifier  
    { {       360}, { 20} }, // class_head             
    { {       358}, { 21} }, // type_name              
    { {       361}, { 22} }, // class_key              
    { {       372}, { 23} }, // identifier             
    { {       260}, { 24} }, // CLASS                  
    { {       288}, { 25} }, // UNION                  
    { {       280}, { 26} }, // STRUCT                 
    { {       257}, { 27} }, // IDENTIFIER             
    { {         0}, {  0} },                           
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 44} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_22[] =
{
    { { REQ_DEF}, {   7} },                   
    { {     363}, {  45} }, // base_clause    
    { {     362}, {  46} }, // class_head_name
    { {      58}, {  47} }, // ':'            
    { {     368}, {  48} }, // class_name     
    { {     372}, {  49} }, // identifier     
    { {     257}, {  27} }, // IDENTIFIER     
    { {       0}, { -50} },                   
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -91} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 50} }, // ';'
    { {        44}, { 51} }, // ','
    { {         0}, {  0} },       
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_31[] =
{
    { { REQ_DEF}, {   4} },                              
    { {     339}, {  52} }, // initializer               
    { {     350}, {  53} }, // brace_or_equal_initializer
    { {      61}, {  54} }, // '='                       
    { {       0}, { -16} },                              
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_33[] =
{
    { { REQ_DEF}, {   4} },                             
    { {     345}, {  55} }, // parameters_and_qualifiers
    { {      91}, {  56} }, // '['                      
    { {      40}, {  57} }, // '('                      
    { {       0}, { -19} },                             
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       341}, { 58} }, // ptr_declarator  
    { {       343}, { 33} }, // noptr_declarator
    { {       342}, { 34} }, // ptr_operator    
    { {       349}, { 35} }, // declarator_id   
    { {        40}, { 36} }, // '('             
    { {        42}, { 37} }, // '*'             
    { {        38}, { 38} }, // '&'             
    { {       372}, { 39} }, // identifier      
    { {       257}, { 27} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       341}, { 59} }, // ptr_declarator  
    { {       343}, { 33} }, // noptr_declarator
    { {       342}, { 34} }, // ptr_operator    
    { {       349}, { 35} }, // declarator_id   
    { {        40}, { 36} }, // '('             
    { {        42}, { 37} }, // '*'             
    { {        38}, { 38} }, // '&'             
    { {       372}, { 39} }, // identifier      
    { {       257}, { 27} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 60} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { DEF_RED}, {  2} },                   
    { {     331}, { 61} }, // declaration_seq
    { {       0}, { -2} },                   
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       372}, { 62} }, // identifier
    { {       123}, { 63} }, // '{'       
    { {       257}, { 27} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 64} }, // '}'
    { {         0}, {  0} },       
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   3} },               
    { {     363}, {  65} }, // base_clause
    { {      58}, {  47} }, // ':'        
    { {       0}, { -52} },               
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 12} },                       
    { {       364}, { 66} }, // base_specifier_list
    { {       365}, { 67} }, // base_specifier     
    { {       366}, { 68} }, // base_type_specifier
    { {       291}, { 69} }, // VIRTUAL            
    { {       367}, { 70} }, // access_specifier   
    { {       368}, { 71} }, // class_name         
    { {       272}, { 72} }, // PRIVATE            
    { {       273}, { 73} }, // PROTECTED          
    { {       274}, { 74} }, // PUBLIC             
    { {       372}, { 49} }, // identifier         
    { {       257}, { 27} }, // IDENTIFIER         
    { {         0}, {  0} },                       
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 12} },                    
    { {       338}, { 75} }, // init_declarator 
    { {       340}, { 31} }, // declarator      
    { {       341}, { 32} }, // ptr_declarator  
    { {       343}, { 33} }, // noptr_declarator
    { {       342}, { 34} }, // ptr_operator    
    { {       349}, { 35} }, // declarator_id   
    { {        40}, { 36} }, // '('             
    { {        42}, { 37} }, // '*'             
    { {        38}, { 38} }, // '&'             
    { {       372}, { 39} }, // identifier      
    { {       257}, { 27} }, // IDENTIFIER      
    { {         0}, {  0} },                    
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 23} },                       
    { {       351}, { 76} }, // initializer_clause 
    { {       344}, { 77} }, // expression         
    { {       369}, { 78} }, // term               
    { {       370}, { 79} }, // literal            
    { {       372}, { 80} }, // identifier         
    { {       371}, { 81} }, // operand            
    { {        40}, { 82} }, // '('                
    { {       294}, { 83} }, // STRING_LITERAL     
    { {       295}, { 84} }, // CHARACTER_LITERAL  
    { {       296}, { 85} }, // INTEGER_LITERAL    
    { {       297}, { 86} }, // HEXADECIMAL_LITERAL
    { {       298}, { 87} }, // OCTAL_LITERAL      
    { {       299}, { 88} }, // FLOAT_LITERAL      
    { {       257}, { 27} }, // IDENTIFIER         
    { {        43}, { 89} }, // '+'                
    { {        45}, { 90} }, // '-'                
    { {        42}, { 91} }, // '*'                
    { {        47}, { 92} }, // '/'                
    { {        37}, { 93} }, // '%'                
    { {        94}, { 94} }, // '^'                
    { {        63}, { 95} }, // '?'                
    { {        58}, { 96} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {       344}, { 97} }, // expression         
    { {       369}, { 78} }, // term               
    { {       370}, { 79} }, // literal            
    { {       372}, { 80} }, // identifier         
    { {       371}, { 81} }, // operand            
    { {        40}, { 82} }, // '('                
    { {       294}, { 83} }, // STRING_LITERAL     
    { {       295}, { 84} }, // CHARACTER_LITERAL  
    { {       296}, { 85} }, // INTEGER_LITERAL    
    { {       297}, { 86} }, // HEXADECIMAL_LITERAL
    { {       298}, { 87} }, // OCTAL_LITERAL      
    { {       299}, { 88} }, // FLOAT_LITERAL      
    { {       257}, { 27} }, // IDENTIFIER         
    { {        43}, { 89} }, // '+'                
    { {        45}, { 90} }, // '-'                
    { {        42}, { 91} }, // '*'                
    { {        47}, { 92} }, // '/'                
    { {        37}, { 93} }, // '%'                
    { {        94}, { 94} }, // '^'                
    { {        63}, { 95} }, // '?'                
    { {        58}, { 96} }, // ':'                
    { {         0}, {  0} },                       
};

SR__ s_57[] =
{
    { { DEF_RED}, {   2} },                                
    { {     348}, {  98} }, // parameter_declaration_clause
    { {       0}, { -29} },                                
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 99} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { DEF_RED}, {   2} },                   
    { {     331}, { 100} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  27} },                                
    { {       125}, { 101} }, // '}'                         
    { {       332}, {   3} }, // declaration                 
    { {       333}, {   4} }, // block_declaration           
    { {       352}, {   5} }, // namespace_definition        
    { {       334}, {   6} }, // simple_declaration          
    { {       353}, {   7} }, // named_namespace_definition  
    { {       354}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       335}, {  10} }, // decl_specifier_seq          
    { {       270}, {  11} }, // NAMESPACE                   
    { {       268}, {  12} }, // INLINE                      
    { {       355}, {  13} }, // type_specifier              
    { {       336}, {  14} }, // decl_specifier              
    { {       356}, {  15} }, // trailing_type_specifier     
    { {       359}, {  16} }, // class_specifier             
    { {       267}, {  17} }, // FRIEND                      
    { {       285}, {  18} }, // TYPEDEF                     
    { {       357}, {  19} }, // simple_type_specifier       
    { {       360}, {  20} }, // class_head                  
    { {       358}, {  21} }, // type_name                   
    { {       361}, {  22} }, // class_key                   
    { {       372}, {  23} }, // identifier                  
    { {       260}, {  24} }, // CLASS                       
    { {       288}, {  25} }, // UNION                       
    { {       280}, {  26} }, // STRUCT                      
    { {       257}, {  27} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       123}, { 102} }, // '{'
    { {         0}, {   0} },       
};

SR__ s_63[] =
{
    { { DEF_RED}, {   2} },                   
    { {     331}, { 103} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 104} }, // ','
    { {       0}, { -55} },       
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {   9} },                       
    { {       366}, { 105} }, // base_type_specifier
    { {       367}, { 106} }, // access_specifier   
    { {       368}, {  71} }, // class_name         
    { {       272}, {  72} }, // PRIVATE            
    { {       273}, {  73} }, // PROTECTED          
    { {       274}, {  74} }, // PUBLIC             
    { {       372}, {  49} }, // identifier         
    { {       257}, {  27} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {   6} },                       
    { {       366}, { 107} }, // base_type_specifier
    { {       291}, { 108} }, // VIRTUAL            
    { {       368}, {  71} }, // class_name         
    { {       372}, {  49} }, // identifier         
    { {       257}, {  27} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_77[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     369}, { 109} }, // term               
    { {     370}, {  79} }, // literal            
    { {     372}, {  80} }, // identifier         
    { {     371}, {  81} }, // operand            
    { {      40}, {  82} }, // '('                
    { {     294}, {  83} }, // STRING_LITERAL     
    { {     295}, {  84} }, // CHARACTER_LITERAL  
    { {     296}, {  85} }, // INTEGER_LITERAL    
    { {     297}, {  86} }, // HEXADECIMAL_LITERAL
    { {     298}, {  87} }, // OCTAL_LITERAL      
    { {     299}, {  88} }, // FLOAT_LITERAL      
    { {     257}, {  27} }, // IDENTIFIER         
    { {      43}, {  89} }, // '+'                
    { {      45}, {  90} }, // '-'                
    { {      42}, {  91} }, // '*'                
    { {      47}, {  92} }, // '/'                
    { {      37}, {  93} }, // '%'                
    { {      94}, {  94} }, // '^'                
    { {      63}, {  95} }, // '?'                
    { {      58}, {  96} }, // ':'                
    { {       0}, { -37} },                       
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {       344}, { 110} }, // expression         
    { {       369}, {  78} }, // term               
    { {       370}, {  79} }, // literal            
    { {       372}, {  80} }, // identifier         
    { {       371}, {  81} }, // operand            
    { {        40}, {  82} }, // '('                
    { {       294}, {  83} }, // STRING_LITERAL     
    { {       295}, {  84} }, // CHARACTER_LITERAL  
    { {       296}, {  85} }, // INTEGER_LITERAL    
    { {       297}, {  86} }, // HEXADECIMAL_LITERAL
    { {       298}, {  87} }, // OCTAL_LITERAL      
    { {       299}, {  88} }, // FLOAT_LITERAL      
    { {       257}, {  27} }, // IDENTIFIER         
    { {        43}, {  89} }, // '+'                
    { {        45}, {  90} }, // '-'                
    { {        42}, {  91} }, // '*'                
    { {        47}, {  92} }, // '/'                
    { {        37}, {  93} }, // '%'                
    { {        94}, {  94} }, // '^'                
    { {        63}, {  95} }, // '?'                
    { {        58}, {  96} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -88} }, 
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -89} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -90} }, 
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {        93}, { 111} }, // ']'                
    { {       369}, { 109} }, // term               
    { {       370}, {  79} }, // literal            
    { {       372}, {  80} }, // identifier         
    { {       371}, {  81} }, // operand            
    { {        40}, {  82} }, // '('                
    { {       294}, {  83} }, // STRING_LITERAL     
    { {       295}, {  84} }, // CHARACTER_LITERAL  
    { {       296}, {  85} }, // INTEGER_LITERAL    
    { {       297}, {  86} }, // HEXADECIMAL_LITERAL
    { {       298}, {  87} }, // OCTAL_LITERAL      
    { {       299}, {  88} }, // FLOAT_LITERAL      
    { {       257}, {  27} }, // IDENTIFIER         
    { {        43}, {  89} }, // '+'                
    { {        45}, {  90} }, // '-'                
    { {        42}, {  91} }, // '*'                
    { {        47}, {  92} }, // '/'                
    { {        37}, {  93} }, // '%'                
    { {        94}, {  94} }, // '^'                
    { {        63}, {  95} }, // '?'                
    { {        58}, {  96} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 112} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  27} },                                
    { {       125}, { 113} }, // '}'                         
    { {       332}, {   3} }, // declaration                 
    { {       333}, {   4} }, // block_declaration           
    { {       352}, {   5} }, // namespace_definition        
    { {       334}, {   6} }, // simple_declaration          
    { {       353}, {   7} }, // named_namespace_definition  
    { {       354}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       335}, {  10} }, // decl_specifier_seq          
    { {       270}, {  11} }, // NAMESPACE                   
    { {       268}, {  12} }, // INLINE                      
    { {       355}, {  13} }, // type_specifier              
    { {       336}, {  14} }, // decl_specifier              
    { {       356}, {  15} }, // trailing_type_specifier     
    { {       359}, {  16} }, // class_specifier             
    { {       267}, {  17} }, // FRIEND                      
    { {       285}, {  18} }, // TYPEDEF                     
    { {       357}, {  19} }, // simple_type_specifier       
    { {       360}, {  20} }, // class_head                  
    { {       358}, {  21} }, // type_name                   
    { {       361}, {  22} }, // class_key                   
    { {       372}, {  23} }, // identifier                  
    { {       260}, {  24} }, // CLASS                       
    { {       288}, {  25} }, // UNION                       
    { {       280}, {  26} }, // STRUCT                      
    { {       257}, {  27} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_102[] =
{
    { { DEF_RED}, {   2} },                   
    { {     331}, { 114} }, // declaration_seq
    { {       0}, {  -2} },                   
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {  27} },                                
    { {       125}, { 115} }, // '}'                         
    { {       332}, {   3} }, // declaration                 
    { {       333}, {   4} }, // block_declaration           
    { {       352}, {   5} }, // namespace_definition        
    { {       334}, {   6} }, // simple_declaration          
    { {       353}, {   7} }, // named_namespace_definition  
    { {       354}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       335}, {  10} }, // decl_specifier_seq          
    { {       270}, {  11} }, // NAMESPACE                   
    { {       268}, {  12} }, // INLINE                      
    { {       355}, {  13} }, // type_specifier              
    { {       336}, {  14} }, // decl_specifier              
    { {       356}, {  15} }, // trailing_type_specifier     
    { {       359}, {  16} }, // class_specifier             
    { {       267}, {  17} }, // FRIEND                      
    { {       285}, {  18} }, // TYPEDEF                     
    { {       357}, {  19} }, // simple_type_specifier       
    { {       360}, {  20} }, // class_head                  
    { {       358}, {  21} }, // type_name                   
    { {       361}, {  22} }, // class_key                   
    { {       372}, {  23} }, // identifier                  
    { {       260}, {  24} }, // CLASS                       
    { {       288}, {  25} }, // UNION                       
    { {       280}, {  26} }, // STRUCT                      
    { {       257}, {  27} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {  11} },                       
    { {       365}, { 116} }, // base_specifier     
    { {       366}, {  68} }, // base_type_specifier
    { {       291}, {  69} }, // VIRTUAL            
    { {       367}, {  70} }, // access_specifier   
    { {       368}, {  71} }, // class_name         
    { {       272}, {  72} }, // PRIVATE            
    { {       273}, {  73} }, // PROTECTED          
    { {       274}, {  74} }, // PUBLIC             
    { {       372}, {  49} }, // identifier         
    { {       257}, {  27} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {   5} },                       
    { {       366}, { 117} }, // base_type_specifier
    { {       368}, {  71} }, // class_name         
    { {       372}, {  49} }, // identifier         
    { {       257}, {  27} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   5} },                       
    { {       366}, { 118} }, // base_type_specifier
    { {       368}, {  71} }, // class_name         
    { {       372}, {  49} }, // identifier         
    { {       257}, {  27} }, // IDENTIFIER         
    { {         0}, {   0} },                       
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {        41}, { 119} }, // ')'                
    { {       369}, { 109} }, // term               
    { {       370}, {  79} }, // literal            
    { {       372}, {  80} }, // identifier         
    { {       371}, {  81} }, // operand            
    { {        40}, {  82} }, // '('                
    { {       294}, {  83} }, // STRING_LITERAL     
    { {       295}, {  84} }, // CHARACTER_LITERAL  
    { {       296}, {  85} }, // INTEGER_LITERAL    
    { {       297}, {  86} }, // HEXADECIMAL_LITERAL
    { {       298}, {  87} }, // OCTAL_LITERAL      
    { {       299}, {  88} }, // FLOAT_LITERAL      
    { {       257}, {  27} }, // IDENTIFIER         
    { {        43}, {  89} }, // '+'                
    { {        45}, {  90} }, // '-'                
    { {        42}, {  91} }, // '*'                
    { {        47}, {  92} }, // '/'                
    { {        37}, {  93} }, // '%'                
    { {        94}, {  94} }, // '^'                
    { {        63}, {  95} }, // '?'                
    { {        58}, {  96} }, // ':'                
    { {         0}, {   0} },                       
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_112[] =
{
    { { REQ_DEF}, {  15} },                            
    { {     346}, { 120} }, // cv_qualifier_seq        
    { {     347}, { 121} }, // exception_especification
    { {      59}, { -25} }, // ';'                     
    { {      44}, { -25} }, // ','                     
    { {      91}, { -25} }, // '['                     
    { {      41}, { -25} }, // ')'                     
    { {      40}, { -25} }, // '('                     
    { {      61}, { -25} }, // '='                     
    { {       0}, { -31} },                            
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {  27} },                                
    { {       125}, { 122} }, // '}'                         
    { {       332}, {   3} }, // declaration                 
    { {       333}, {   4} }, // block_declaration           
    { {       352}, {   5} }, // namespace_definition        
    { {       334}, {   6} }, // simple_declaration          
    { {       353}, {   7} }, // named_namespace_definition  
    { {       354}, {   8} }, // unnamed_namespace_definition
    { {        59}, {   9} }, // ';'                         
    { {       335}, {  10} }, // decl_specifier_seq          
    { {       270}, {  11} }, // NAMESPACE                   
    { {       268}, {  12} }, // INLINE                      
    { {       355}, {  13} }, // type_specifier              
    { {       336}, {  14} }, // decl_specifier              
    { {       356}, {  15} }, // trailing_type_specifier     
    { {       359}, {  16} }, // class_specifier             
    { {       267}, {  17} }, // FRIEND                      
    { {       285}, {  18} }, // TYPEDEF                     
    { {       357}, {  19} }, // simple_type_specifier       
    { {       360}, {  20} }, // class_head                  
    { {       358}, {  21} }, // type_name                   
    { {       361}, {  22} }, // class_key                   
    { {       372}, {  23} }, // identifier                  
    { {       260}, {  24} }, // CLASS                       
    { {       288}, {  25} }, // UNION                       
    { {       280}, {  26} }, // STRUCT                      
    { {       257}, {  27} }, // IDENTIFIER                  
    { {         0}, {   0} },                                
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_120[] =
{
    { { REQ_DEF}, {   8} },                            
    { {     347}, { 123} }, // exception_especification
    { {      59}, { -26} }, // ';'                     
    { {      44}, { -26} }, // ','                     
    { {      91}, { -26} }, // '['                     
    { {      41}, { -26} }, // ')'                     
    { {      40}, { -26} }, // '('                     
    { {      61}, { -26} }, // '='                     
    { {       0}, { -31} },                            
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_123[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,
};

} // anonymous namespace ends


// $insert namespace-open
namespace opwig
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

MDParserBase::MDParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void MDParser::print__()
{
// $insert print
}

void MDParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void MDParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void MDParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void MDParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void MDParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t MDParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void MDParser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 112 "mdparser.gr"
        {
         for (auto it: *d_vsp__[0].data<Tag__::DeclarationSeq>())
         if (!(it) (global_namespace_))
         std::cout << "Namespace action failed (global)";
         }
        break;

        case 2:
#line 120 "mdparser.gr"
        {
         d_val__.get<Tag__::DeclarationSeq>() = std::shared_ptr<ScopeActionList>(new ScopeActionList);
         }
        break;

        case 3:
#line 124 "mdparser.gr"
        {
         (d_vsp__[-1].data<Tag__::DeclarationSeq>())->push_back(d_vsp__[0].data<Tag__::Declaration>());
         d_val__.get<Tag__::DeclarationSeq>() = d_vsp__[-1].data<Tag__::DeclarationSeq>();
         }
        break;

        case 4:
#line 131 "mdparser.gr"
        {
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 5:
#line 135 "mdparser.gr"
        { 
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 6:
#line 145 "mdparser.gr"
        { d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>(); }
        break;

        case 8:
#line 151 "mdparser.gr"
        {
         TypeAction type_action = d_vsp__[-2].data<Tag__::Type>();
         std::shared_ptr<parser::DeclaratorList> init_list = d_vsp__[-1].data<Tag__::DeclaratorSeq>();
         d_val__.get<Tag__::Declaration>() = [type_action, init_list] (md::Ptr<md::Scope> current_namespace) -> bool {
         for (auto declarator: *init_list) {
         std::string type = type_action(current_namespace);
         if (declarator.has_parameters()) {
         md::Ptr<md::Function> func =
         md::Function::Create(declarator.name(), type, declarator.parameters());
         if (!current_namespace->AddNestedFunction(func))
         std::cout << "FAIL\n";
         else
         std::cout << "SUCCESS\n";
         } else {
         md::Ptr<md::Variable> var = md::Variable::Create(declarator.name(), type);
         if (!current_namespace->AddGlobalVariable(var)) {
         
         }
         }
         }
         return true;
         };
         }
        break;

        case 9:
#line 175 "mdparser.gr"
        {
         TypeAction type_action = d_vsp__[-1].data<Tag__::Type>();
         d_val__.get<Tag__::Declaration>() = [type_action] (md::Ptr<md::Scope> current_namespace) -> bool {
         type_action(current_namespace);
         return true;
         };
         }
        break;

        case 10:
#line 187 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 11:
#line 189 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 14:
#line 201 "mdparser.gr"
        {
         d_val__.get<Tag__::DeclaratorSeq>() = std::shared_ptr<parser::DeclaratorList>(new parser::DeclaratorList);
         (d_val__.get<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         }
        break;

        case 15:
#line 206 "mdparser.gr"
        {
         (d_vsp__[-2].data<Tag__::DeclaratorSeq>())->push_back(d_vsp__[0].data<Tag__::Declarator>());
         d_val__.get<Tag__::DeclaratorSeq>() = d_vsp__[-2].data<Tag__::DeclaratorSeq>();
         }
        break;

        case 16:
#line 213 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 17:
#line 215 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 18:
#line 219 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 19:
#line 223 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 20:
#line 225 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[0].data<Tag__::Declarator>(); }
        break;

        case 21:
#line 229 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = parser::Declarator(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 22:
#line 231 "mdparser.gr"
        {
         d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>();
         (d_val__.get<Tag__::Declarator>()).set_parameters(*d_vsp__[0].data<Tag__::ParameterSeq>());
         }
        break;

        case 23:
#line 236 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-3].data<Tag__::Declarator>(); }
        break;

        case 24:
#line 238 "mdparser.gr"
        { d_val__.get<Tag__::Declarator>() = d_vsp__[-1].data<Tag__::Declarator>(); }
        break;

        case 25:
#line 242 "mdparser.gr"
        { d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-1].data<Tag__::ParameterSeq>(); }
        break;

        case 26:
#line 244 "mdparser.gr"
        { d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-2].data<Tag__::ParameterSeq>(); }
        break;

        case 27:
#line 246 "mdparser.gr"
        { d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-2].data<Tag__::ParameterSeq>(); }
        break;

        case 28:
#line 248 "mdparser.gr"
        { d_val__.get<Tag__::ParameterSeq>() = d_vsp__[-3].data<Tag__::ParameterSeq>(); }
        break;

        case 29:
#line 252 "mdparser.gr"
        {
         d_val__.get<Tag__::ParameterSeq>() = std::shared_ptr<md::ParameterList>(new md::ParameterList);
         }
        break;

        case 30:
#line 258 "mdparser.gr"
        {}
        break;

        case 31:
#line 262 "mdparser.gr"
        {}
        break;

        case 34:
#line 272 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 38:
#line 313 "mdparser.gr"
        {
         d_val__.get<Tag__::Declaration>() = d_vsp__[0].data<Tag__::Declaration>();
         }
        break;

        case 39:
#line 317 "mdparser.gr"
        {
         d_val__.get<Tag__::Declaration>() = [] (md::Ptr<md::Scope> current_namespace) -> bool { return true; };
         }
        break;

        case 40:
#line 323 "mdparser.gr"
        {
         using md::Namespace;
         using md::Ptr;
         Ptr<Namespace> new_namespace = Namespace::Create();
         std::string name = d_vsp__[-3].data<Tag__::String>();
         for (auto it: *d_vsp__[-1].data<Tag__::DeclarationSeq>())
         if (!(it) (new_namespace))
         std::cout << "Namespace action failed (new)";
         d_val__.get<Tag__::Declaration>() = [name,new_namespace] (Ptr<md::Scope> current_namespace) -> bool {
         return current_namespace->AddNestedNamespace(name, new_namespace);
         };
         }
        break;

        case 44:
#line 348 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 45:
#line 350 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 46:
#line 354 "mdparser.gr"
        { d_val__.get<Tag__::Type>() = d_vsp__[0].data<Tag__::Type>(); }
        break;

        case 47:
#line 358 "mdparser.gr"
        { 
         std::string name = d_vsp__[0].data<Tag__::String>();
         d_val__.get<Tag__::Type>() = [name] (md::Ptr<md::Scope> current_namespace) -> std::string {
         return name;
         }; 
         }
        break;

        case 48:
#line 367 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 49:
#line 373 "mdparser.gr"
        {
         md::Ptr<md::Class> classObj = d_vsp__[-2].data<Tag__::Class>();
         d_val__.get<Tag__::Type>() = [classObj] (md::Ptr<md::Scope> current_namespace) -> std::string {
         if (current_namespace->AddNestedClass(classObj->name(), classObj))
         return classObj->name();
         throw md::SemanticError("Non-anonymous class cannot have empty name!");
         };
         }
        break;

        case 50:
#line 384 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create("", BaseSpecifierList()); }
        break;

        case 51:
#line 386 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create("", *d_vsp__[0].data<Tag__::BaseSpecifierSeq>()); }
        break;

        case 52:
#line 388 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create(d_vsp__[0].data<Tag__::String>(), BaseSpecifierList()); }
        break;

        case 53:
#line 390 "mdparser.gr"
        { d_val__.get<Tag__::Class>() = md::Class::Create(d_vsp__[-1].data<Tag__::String>(), *d_vsp__[0].data<Tag__::BaseSpecifierSeq>()); }
        break;

        case 54:
#line 394 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 55:
#line 398 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifierSeq>() = d_vsp__[0].data<Tag__::BaseSpecifierSeq>(); }
        break;

        case 56:
#line 402 "mdparser.gr"
        {
         d_val__.get<Tag__::BaseSpecifierSeq>() = std::shared_ptr<BaseSpecifierList>(new BaseSpecifierList);
         (d_val__.get<Tag__::BaseSpecifierSeq>())->push_back(d_vsp__[0].data<Tag__::BaseSpecifier>());
         }
        break;

        case 57:
#line 407 "mdparser.gr"
        {
         (d_vsp__[-2].data<Tag__::BaseSpecifierSeq>())->push_back(d_vsp__[0].data<Tag__::BaseSpecifier>());
         d_val__.get<Tag__::BaseSpecifierSeq>() = d_vsp__[-2].data<Tag__::BaseSpecifierSeq>();
         }
        break;

        case 58:
#line 414 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>()); }
        break;

        case 59:
#line 416 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true); }
        break;

        case 60:
#line 418 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), d_vsp__[-1].data<Tag__::AccessSpecifier>()); }
        break;

        case 61:
#line 420 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true, d_vsp__[-1].data<Tag__::AccessSpecifier>()); }
        break;

        case 62:
#line 422 "mdparser.gr"
        { d_val__.get<Tag__::BaseSpecifier>() = parser::BaseSpecifier(d_vsp__[0].data<Tag__::String>(), true, d_vsp__[-2].data<Tag__::AccessSpecifier>()); }
        break;

        case 63:
#line 426 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 64:
#line 430 "mdparser.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = parser::AccessSpecifier::PRIVATE; }
        break;

        case 65:
#line 432 "mdparser.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = parser::AccessSpecifier::PROTECTED; }
        break;

        case 66:
#line 434 "mdparser.gr"
        { d_val__.get<Tag__::AccessSpecifier>() = parser::AccessSpecifier::PUBLIC; }
        break;

        case 67:
#line 438 "mdparser.gr"
        { d_val__.get<Tag__::String>() = d_vsp__[0].data<Tag__::String>(); }
        break;

        case 91:
#line 483 "mdparser.gr"
        {
         d_val__.get<Tag__::String>() = d_scanner.matched();
         }
        break;

    }
}

inline void MDParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void MDParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int MDParser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void MDParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int MDParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}


// $insert namespace-close
}


