
set (OUROBOROS_LANG_PACKAGE_lua     Lua51)
set (OUROBOROS_LANG_FOUND_lua       LUA51_FOUND)
set (OUROBOROS_LANG_LONGNAME_lua    Lua5.1)
set (OUROBOROS_LANG_INCLUDE_DIR_lua LUA_INCLUDE_DIR)

set (OUROBOROS_LANG_PACKAGE_python      "PythonLibs 2.6")
set (OUROBOROS_LANG_FOUND_python        PYTHONLIBS_FOUND)
set (OUROBOROS_LANG_LONGNAME_python     Python2.6)
set (OUROBOROS_LANG_INCLUDE_DIR_python  PYTHON_INCLUDE_DIRS)

set (OUROBOROS_LANGS lua python)

function (ouroboros_wrap_module MODULE_NAME OUTDIR GENERATED_SRC_VAR)
  foreach (LANGUAGE IN OUROBOROS_LANGS)
    message (STATUS "Wrapping module ${MODULE_NAME}")
    message (STATUS ${OUROBOROS_LANG_PACKAGE_${LANGUAGE}})
    message (STATUS ${OUROBOROS_LANG_FOUND_${LANGUAGE}})
    message (STATUS ${OUROBOROS_LANG_LONGNAME_${LANGUAGE}})
    message (STATUS ${OUROBOROS_LANG_INCLUDE_DIR_${LANGUAGE}})
    find_package (${OUROBOROS_LANG_PACKAGE_${LANGUAGE}})
    if (NOT ${OUROBOROS_LANG_FOUND_${LANGUAGE}})
      message (FATAL_ERROR "Could not find ${OUROBOROS_LANG_LONGNAME_${LANGUAGE}}")
    endif (NOT ${OUROBOROS_LANG_FOUND_${LANGUAGE}})
    message (STATUS ${${OUROBOROS_LANG_FOUND_${LANGUAGE}}})
    message (STATUS ${${OUROBOROS_LANG_INCLUDE_DIR_${LANGUAGE}}})
    include_directories (${${OUROBOROS_LANG_INCLUDE_DIR_${LANGUAGE}}})
  endforeach(LANGUAGE
endfunction (ouroboros_wrap_module)

